/**
 * 中文界面文案集中定义（单文件，便于业务侧「像改配置一样」调整措辞）。
 * 新增页面/菜单时：先在此补充字段，再在组件中引用 `zhCN.xxx`，避免散落硬编码。
 *
 * 文件上传页（示例）：
 * - 页标题、页内说明、批次配置、队列、按钮等 → `importUpload`
 * - 虚线拖拽区主文案、选文件/选文件夹、命名说明 → `uploadZone`
 */
export const zhCN = {
  common: {
    soon: '待开发',
    /** 已立项/可进入，功能迭代中 */
    inProgress: '开发中',
    logout: '退出',
    help: '帮助',
  },

  login: {
    brandSub: '票鉴 · 发票大数据审计分析',
    sep: '请登录后继续',
    /** Phase 1 演示用；接入 FastAPI 后由服务端校验与返回用户信息 */
    /** 当前为便于验证：账号、密码均为空字符串时视为演示登录通过 */
    demoUsername: '',
    demoPassword: '',
    demoTip:
      '演示：账号与密码均留空即可登录（Phase 1 原型）。填写任意内容将按错误账号处理。',
    /** 避免与浏览器自动填充冲突时的一键入口 */
    demoOneClick: '免填账号，直接登录',
    demoDisplayName: '管理员',
    demoRole: '管理员',
    accountLabel: '账号',
    passwordLabel: '密码',
    accountPlaceholder: '请输入账号',
    passwordPlaceholder: '请输入密码',
    remember: '记住我',
    forgotPassword: '忘记密码',
    submit: '登录',
    footnote: '本地离线运行 · 权限与审计留痕用于控制危险操作',
    errorInvalid: '账号或密码错误',
  },

  shell: {
    /** 产品英文名（Logo、alt、部分标题） */
    appNameEn: 'InvoiceLens',
    /** 浏览器标签页标题（与 `index.html` 默认 title 保持一致，运行时在入口同步） */
    documentTitle: 'InvoiceLens · 票鉴',
    sidebarCollapseTitle: '收起/展开侧边栏',
    brandSub: '票鉴 · 发票大数据分析工具',
    licenseTag: '专业版 · 有效期 2025-12-31',
  },

  sidebar: {
    sectionPrep: '数据准备',
    sectionAnalysis: '分析看板',
    sectionOutput: '输出',
    sectionSystem: '系统',
    invoiceData: '发票数据',
    fieldMapping: '字段映射配置',
    mappingConfig: 'ODS层映射配置',
    mappingTemplates: '模板管理',
    importWizard: '发票导入向导',
    fileUpload: '文件上传',
    dataPreview: 'ODS数据查看',
    formatCheck: '格式检测',
    processingCenter: '加工中心',
    odsToDwd: 'ODS→DWD',
    dwdDataPreview: 'DWD数据查看',
    historyBatches: '历史批次记录',
    qualityReport: '数据质量报告',
    qualityOverview: '质量概览',
    qualityDetail: '异常明细',
    qualityTrend: '质量趋势',
    invoiceExport: '发票数据导出',
    dimMgmt: '维度管理',
    badgeNew: '新',
    dimOrg: '企业组织维度',
    dimOrgTree: '管理树',
    dimEquityTree: '产权树',
    dimOrgDiff: '管产差异分析',
    dimTaxCode: '税收分类编码',
    dimTaxLib: '编码库管理',
    dimTaxCoverage: '覆盖率分析',
    dimDict: '数据字典维护',
    dimVersion: '年度版本管理',
    overview: '数据概览',
    ovSummary: '整体汇总',
    ovTrend: '月度趋势',
    ovTax: '税率结构',
    supplier: '供应商分析',
    supplierCr: '集中度（CR值）',
    supplierTop: 'Top 供应商明细',
    supplierNew: '新增/消失供应商',
    flags: '审计疑点',
    flagsList: '疑点清单',
    flagsRules: '规则配置',
    flagsTrack: '疑点跟踪',
    related: '关联交易',
    relatedGraph: '图谱分析',
    relatedPairs: '对开发票',
    relatedShell: '通道公司识别',
    finance: '财务校验',
    financeReconcile: '发票与账表核对',
    financeDiff: '差异分析',
    compare: '子公司对比',
    compareRank: '评级排名',
    compareCharts: '横向对比图表',
    report: '生成报告',
    reportConfig: '报告配置',
    reportTemplates: '报告模板管理',
    reportArchive: '历史报告存档',
    users: '用户管理',
    usersList: '用户列表',
    usersRoles: '角色权限配置',
    usersAudit: '操作日志',
    settings: '系统设置',
    settingsThresholds: '规则阈值',
    settingsLicense: '授权管理',
    settingsInstance: '实例配置',
  },

  breadcrumb: {
    invoiceData: '发票数据',
    importWizard: '发票导入向导',
    fileUpload: '文件上传',
    formatCheck: '格式检测',
    dataPreview: 'ODS数据查看',
    processingCenter: '加工中心',
    odsToDwd: 'ODS→DWD',
    dwdDataPreview: 'DWD数据查看',
    historyBatches: '历史批次记录',
    fieldMapping: '字段映射配置',
    mappingConfig: 'ODS层映射配置',
    mappingTemplates: '模板管理',
    pending: '待开发',
  },

  /**
   * 字段映射配置（高保真原型 → 后续对接 API / 写回 YAML）
   */
  fieldMappingUi: {
    prototypeBadge: '界面原型',
    sourceLive: '已接通',
    sourceOffline: '离线',
    sourceLabelPrefix: '来源：',
    loadFromApiFailed: '无法从本地 API 加载字段映射，已显示内置兜底配置。',
    apiUnavailableHint:
      '说明：该能力已实现。开发模式（npm run dev）下默认通过 Vite 将「同源 /api」代理到 127.0.0.1:8765，请先运行 dev.bat 或 dev.bat api 启动本地 API。若仍失败：检查 8765 是否监听、是否被防火墙拦截；或在前端 .env 设置 VITE_LOCAL_API_BASE 为完整地址（将绕过代理直连）。',
    refreshFailed: '从服务器刷新失败。',
    saveSuccess: '已保存到 field_mapping.yaml。',
    saveSuccessWithPath: '已保存：{path}',
    saveFailed: '保存失败',
    busyLoading: '加载中…',
    busySaving: '保存中…',
    saveTooltip: '将当前编辑写回 config/field_mapping.yaml（会先备份 .bak）',
    saveDisabledNoChanges: '没有未保存的修改',
    configPageTitle: 'ODS层映射配置',
    configPageBody:
      '维护「标准字段（建议与 ODS 列名一致）↔ 业务含义（label_zh）与表头别名（aliases）」对照关系，供格式检测与 Excel→ODS 使用。打开本页会从本地 API 拉取 config/field_mapping.yaml；可编辑已有字段，在「全局默认」下可用「添加字段」；在「按 Sheet 类型」下还可使用「表头检测」对照样例 Excel 补键。保存后写回磁盘并保留 sheet_header_slugs 等未编辑块。',
    configYamlHint:
      '配置文件路径：项目根目录 config/field_mapping.yaml。修改后可在「文件上传」页使用「刷新映射」或重启本地 API 使前端加载最新定义。',
    configOdsDwdHint:
      '设计建议：ODS 层字段命名尽量稳定、语义清晰，后续 DWD 可在同义列上叠加清洗规则（如丢弃「序号」、补充维度外键），避免在 DWD 再猜 Excel 原始表头。',
    toolsBatchHint:
      '批量从样本目录归纳字段可运行：python tools/generate_field_mapping_from_samples.py（详见仓库 README）。',
    contextCardTitle: '配置上下文',
    modeGlobal: '全局默认',
    modeSheet: '按 Sheet 类型',
    modeGlobalHint: '适用于多数票种的默认块；未单独覆盖的 Sheet 类型将回退到此处定义。',
    sheetPickLabel: '选择 Sheet 类型',
    sheetHasOverride: '已有 YAML 独立块',
    gotoUpload: '前往文件上传（验证映射）',
    tableCardTitle: '字段对照表',
    globalCoverageHint:
      '「表头检测」需对照具体样例表：请切换到「按 Sheet 类型」并选定目标 Sheet 后使用。若要把检出列一并写入全局 default，可在导入时选择「当前 Sheet + 全局 default」。',
    sheetContextBanner:
      '当前编辑 Sheet：{name}。仅列出 YAML 中该子块已声明的字段；灰色占位为全局 default 原文（未写入本 Sheet 时生效）。本块有填写则以本块为准。',
    sheetNoBlockRows: '当前 YAML 中尚无该 Sheet 的 `sheets` 子块，或块内无字段；请先在其他工具中生成块，或切换到「全局默认」编辑。',
    searchPlaceholder: '搜索字段 key / 中文名 / 别名…',
    tableSearchNoMatch: '没有符合搜索条件的行。',
    refreshFromServer: '从服务器刷新',
    refreshTooltip: '调用本地 API 重新加载 field_mapping.yaml',
    saveToYaml: '保存到配置',
    saveDisabledTooltip: '没有可保存的修改',
    colOds: 'ODS 标准字段',
    colZhTitle: '业务含义',
    colAliases: '表头别名（多值）',
    colType: '类型',
    colMatch: '匹配',
    colStatus: '状态',
    valueType: {
      string: '文本',
      date: '日期',
      amount: '金额',
    },
    matchMode: {
      /** 与运行时一致：先整表头归一化后与别名等价，否则列名归一化后包含别名子串 */
      exact: '归一化等价',
      contains: '等价或包含',
    },
    requiredTag: '必填',
    statusAligned: '已对齐',
    statusReview: '待复核',
    statusModified: '已修改',
    statusEditing: '编辑中',
    tableFootnote:
      '按 Sheet 编辑时灰色占位为全局 default 原文；本块有 label_zh / aliases 则以本块为准。别名多行、失焦按行解析写回。',
    addFieldToggle: '添加字段',
    addFieldTitle: '新增标准字段',
    addFieldOdsLabel: 'ODS 字段名（蛇形）',
    addFieldOdsPlaceholder: '例如 buyer_email',
    addFieldZhLabel: '业务含义（label_zh）',
    addFieldAliasesLabel: '表头别名（每行一条，可选）',
    addFieldAlsoDefault: '同时写入全局 default',
    addFieldSubmit: '加入当前上下文',
    addFieldCancel: '收起',
    addFieldErr: {
      empty: '请填写 ODS 字段名。',
      invalid: '须为小写蛇形：以小写字母开头，仅含 a–z、0–9、下划线。',
      long: 'ODS 字段名过长。',
      duplicate: '该字段在当前上下文中已存在。',
      duplicateDefault: '全局 default 中已存在该字段名。',
      duplicateSheet: '当前 Sheet 子块中已存在该字段名。',
      needContent: '请至少填写业务含义或一条别名（可仅填业务含义，将同时作为一条别名）。',
    },
    addFieldAlsoDefaultHint:
      '勾选后：完整定义只写入全局 default；当前 Sheet 仅增加「引用 default」的空项（aliases 为空）。',
    coverageToggle: '表头检测（未覆盖列）',
    coverageTitle: '上传样例 .xlsx，列出 YAML 未覆盖的表头并建议英文 key',
    coveragePickFile: '选择 Excel 文件',
    coverageRunning: '检测中…',
    coverageFailed: '检测失败，请确认已启动本地 API 且文件为 .xlsx。',
    coverageEmpty: '未检出未覆盖表头（或所选目标 Sheet 与文件不匹配）。',
    coverageHint: '检出 {n} 条未覆盖列，可选中后导入。',
    coverageSheetCol: '工作表',
    coverageHeaderCol: '表头原文',
    coverageSlugCol: '建议 key（可改）',
    coverageImportTo: '导入到：',
    coverageImportGlobal: '仅全局 default',
    coverageImportSheet: '当前 Sheet 子块',
    coverageImportSheetAndDefault: '当前 Sheet + 全局 default',
    coverageSelectAll: '全选',
    coverageSelectNone: '全不选',
    coverageApply: '导入选中项',
    coverageAlsoNote:
      '选「当前 Sheet + 全局 default」时：若当前 Sheet 对该 key 已有本地 label/别名，则只在 Sheet 中合并；若 Sheet 无本地值（含仅空继承）而 default 已有该 key，则只在 default 中合并；若二者均无该 key 的有效定义，则只在 Sheet 中合并写入。',
    coverageImported: '已合并到当前编辑（未自动保存，请点「保存到配置」）。',
    coverageAbortedInvalidKeys: '存在不合法的英文 key，已取消本批导入，未修改任何数据。',
    addFieldSuccess: '已加入当前编辑（未自动保存）。',
    templatesPageTitle: '模板管理',
    templatesPageBody:
      '管理「样例 Excel 包、列说明、校验规则片段」等可复用资产，便于新项目或新票种快速对齐字段映射。以下为占位卡片，用于评审信息架构与操作动线。',
    templatesInfoBanner:
      '模板与 ODS 层映射的关系：模板提供「样例数据 + 推荐字段清单」，导入「ODS层映射配置」后参与格式检测；不会替代 field_mapping.yaml 作为运行时真源。',
    templateActionSoon: '下一阶段开放',
    downloadSample: '下载样例包',
    applyTemplate: '应用到当前环境',
    uploadPackTitle: '上传自定义模板包',
    uploadPackDesc: '支持 .zip（含样例 xlsx + README + 可选 mapping 片段）。原型阶段仅展示区域。',
    uploadPackPlaceholder: '将模板包拖拽到此处，或点击选择文件（未接通）',
    templateCards: [
      {
        id: 'golden-vat',
        title: '金税增值税发票 · 标准进项',
        desc: '含「发票基础信息 / 信息汇总表」常见列，适用于多数一般纳税人导出格式。',
        scope: '适用：进项 · 金税三/四期',
        version: '版本 1.2',
        updated: '更新：2026-Q1',
      },
      {
        id: 'rail-eticket',
        title: '铁路电子客票 · 扩展块',
        desc: '补充「日期 / 开票日期」等易混列名与金额类字段，与 field_mapping.yaml 中铁路块对应。',
        scope: '适用：铁路电子客票 Sheet',
        version: '版本 0.9',
        updated: '更新：草案',
      },
      {
        id: 'goods-list',
        title: '货物清单 · 明细行',
        desc: '行级明细与汇总表混合场景下的推荐别名集合（占位）。',
        scope: '适用：货物清单',
        version: '版本 0.6',
        updated: '更新：草案',
      },
    ],
  },

  importUpload: {
    title: '文件上传',
    description:
      '将各级企业从金税系统导出的进项与销项发票数据（Excel 文件）加入队列后，请先进行「格式检测」初筛，通过后再「开始导入」写入 ODS；支持金税三期/四期常见格式。',
    batchConfig: '批次配置',
    labelBatchDate: '批次基准日期',
    batchDatePlaceholder: 'YYYYMMDD',
    batchDateHint: '8 位数字，默认当日；将作为导入批次标识（batch_id）提交。',
    labelMaxFileMb: '单文件大小上限（MB）',
    hintMaxFileMb:
      '格式检测与上传均使用该上限；实际生效为「此处数值」与「服务端 INVOICELENS_MAX_UPLOAD_MB」的较小值（当前服务端硬顶 {mb} MB）。参数保存在本浏览器。',
    labelAutoImportAfterFormat: '格式检测后导入ODS',
    optAutoTrigger: '自动触发',
    optManualTrigger: '手动触发',
    labelForceReimport: '重复文件处理',
    forceReimportToggle: '强制重导（忽略判重）',
    hintForceReimport:
      '开启后将忽略“同一文件哈希已成功导入”的判重保护，适用于扩范围补导或修复历史批次。',
    forceReimportWarn:
      '已开启强制重导：本次将忽略重复文件判定，可能写入重复数据。建议使用新批次并在导入备注中记录原因。',
    // 当前阶段 Excel->ODS 不做进/销分流；该选项仅用于后续 DW 阶段区分/标记
    labelDirection: '后续区分标记',
    labelDwd: '完成后 DWD 清洗',
    optDirAuto: '自动识别（后续区分）',
    optDirIn: '强制进项标记（后续区分）',
    optDirOut: '强制销项标记（后续区分）',
    optDwdAuto: '自动触发',
    optDwdManual: '手动触发',
    queue: '当前队列',
    queueEmpty: '暂无文件，请拖拽或点击上传。',
    queueSelectAll: '全选',
    queueRemoveSelected: '移除所选',
    queueRemoveRow: '移除',
    queueRemoveRowTitle: '从队列移除，导入时将跳过该文件',
    pendingImport: '待导入',
    pathNotProvidedHint:
      '出于安全策略，网页无法读取带盘符的绝对路径（如 C:\\…）。使用「选择文件夹」或拖入文件夹时，仅能显示相对路径（相对您所选的那一层文件夹，相当于该批次的「虚拟根」）。',
    pathPlaceholder: '—',
    formatCheck: '格式检测',
    formatCheckPageTitle: '格式检测',
    formatCheckPageBody:
      '在此选文件、勾选目标 Sheet 并执行检测（与上传页同一套规则）：结构/标准字段与 YAML 未覆盖表头分块展示。可在导入前单独完善 field_mapping.yaml；检测通过后可直接进入「文件上传」补批次与失败策略，上传页将视为已通过检测，无需再跑一遍。',
    formatCheckPageCta: '前往文件上传（不携带队列）',
    formatCheckGoUploadPassed: '转至文件上传（已检测通过，上传页不再重复检测）',
    formatCheckParamsCard: '检测参数（单文件上限与目标 Sheet）',
    /** Sheet 覆盖分析子功能（格式检测独立页） */
    sheetCoverageCardTitle: 'Sheet 覆盖分析（子功能）',
    sheetCoverageCardDesc:
      '按 config/sheet_mapping.yaml（与侧栏「刷新映射」一致）中的类型 key，对队列内每个工作簿扫描全部工作表标签：汇总「类型 → 实际出现的表名」，并列出「任一 key 都匹配不到」的物理工作表，便于判断 YAML 是否需补充。',
    sheetCoverageScanButton: '扫描当前队列中的工作表',
    sheetCoverageScanning: '扫描中…',
    /** Sheet 覆盖扫描逐文件进度 */
    sheetCoverageScanningWithProgress: '扫描中 {done}/{total}',
    sheetCoverageNeedQueue: '请先加入至少一个 Excel 文件。',
    sheetCoverageByType: '已知类型（YAML / sheet_mapping）与实际工作表名',
    sheetCoverageMultiMatchHint:
      '同一物理表名可能出现在多行：工作表标签同时命中多个类型 key 的「包含」规则时，与导入链路的表类型判定一致。',
    sheetCoverageColType: '类型 key',
    sheetCoverageColActual: '本队列中出现的实际工作表名（去重）',
    sheetCoverageNoHitInQueue: '（本队列未出现命中该类型的表）',
    /** 已知类型表在隐藏「未命中」行后，若整表无数据时的占位说明 */
    sheetCoverageByTypeEmpty: '本队列中暂无工作表命中已列出的类型 key（相对 sheet_mapping 表名规则）。',
    sheetCoverageUnmapped: '未涵盖在已知类型中的工作表',
    sheetCoverageAllMapped: '当前队列中，所有工作表均至少命中一个已知类型 key。',
    sheetCoverageUnmappedHint:
      '下列工作表名与当前 sheet_mapping 中的任一类型 key 均无法按「表名包含 key」规则匹配。若业务上需要导入这些表，请在 config/sheet_mapping.yaml 等配置中补充类型或调整匹配键。',
    sheetCoveragePerFileDetail: '每个 Excel 里有哪些工作表（逐文件展开）',
    sheetCoveragePerFileDetailIntro:
      '上面的表是「整队列汇总」；这里是「按文件拆开」：逐个文件列出工作簿内全部工作表名。若上面有「未涵盖在已知类型中的工作表」，可在此对照是哪一个文件、哪一张表，便于改 config/sheet_mapping.yaml 或检查金税导出是否缺表。',
    sheetCoverageSheetsInBook: '工作簿内全部工作表',
    sheetCoverageUnmatchedInThisFile: '本文件中未命中已知类型的表',
    formatPassedFromHandoff: '已由「格式检测」页通过校验带入本页，可直接补充批次等信息后「开始导入」，无需再次点击「格式检测」。若修改队列、目标 Sheet、单文件上限或 ODS 层映射配置，将需重新检测。',
    formatChecking: '检测中',
    /** 格式检测逐文件进度：已完成数 / 队列总数 */
    formatCheckingWithProgress: '检测中 {done}/{total}',
    formatPassed: '已通过格式检测，可开始导入。',
    formatFailed: '格式检测未通过，请修正后重新检测。',
    /** 与「YAML 未覆盖表头」分块展示 */
    formatCheckBlockStructure: '结构 / 标准字段问题',
    formatCheckBlockYaml: 'YAML 未覆盖表头（ODS层映射配置）',
    formatCheckYamlHelp:
      '可将表头与建议英文 key 写入 config/field_mapping.yaml 的 sheet_header_slugs，或对样例目录运行 tools/sync_sheet_block_from_samples.py。',
    formatIdleHint:
      '加入文件并勾选目标 Sheet 后，请先点击「格式检测」。.xlsx 将校验：① 必有「发票基础信息」且「信息汇总表/货物清单」至少其一；② 勾选目标对应表的表头是否缺标准字段（对齐 config/field_mapping.yaml，可编辑）。',
    startImport: '开始导入',
    startImportNeedFormat: '请先通过格式检测',
    /** 已通过检测但目标 Sheet 与检测时不一致（或超出已检测范围） */
    startImportTargetSheetsDrift:
      '目标 Sheet 与最近一次格式检测通过时不一致，或包含未检测类型。请重新勾选并执行格式检测后再导入。',
    pause: '暂停',
    importStop: '停止',
    importStopHint: '请求停止拉取事件流（已提交至服务端的任务仍可能继续执行，请在 ODS 批次页核对）',
    importProgress: '导入进度',
    importFailures: '失败记录',
    resumeImport: '继续导入',
    importingNow: '导入中…',
    importPhaseUpload: '正在上传文件 {cur}/{total}…',
    importPhaseProcessing: '上传完成，正在执行导入…',
    importRunErrorTitle: '导入未能完成',
    importEventsStreamError: '未能正常拉取导入事件流，请确认本地 API 仍在运行后重试；必要时查看服务端日志或在「ODS 批次与会话」核对是否已部分落库。',
    importNoSessionEnd: '未收到会话结束事件，无法汇总结果。请查看服务端日志或在「ODS 批次与会话」核对。',
    importFailuresEmpty: '暂无失败记录',
    failureActionStop: '停下来',
    failureActionSkip: '跳过该 Excel',
    targetSheets: '目标 Sheet 范围（Excel→ODS）',
    targetSheetsSelectAll: '全选',
    /** 有格式检测范围锁时「全选」按钮的说明 */
    targetSheetsSelectAllWithinFormatScope: '仅勾选最近一次格式检测所允许的类型（与「转至文件上传」带入的范围一致），不含未检测项。',
    targetSheetsClearAll: '清空',
    targetSheetsRefresh: '刷新映射',
    /** 目标 Sheet 勾选框禁用时的 title */
    targetSheetLockedNotInFormatScope:
      '该类型未包含在最近一次通过的格式检测范围内。请返回「格式检测」页勾选并检测，或在本页变更队列后重新执行格式检测。',
    /** 有范围锁时显示在勾选区下方的提示条 */
    targetSheetsScopeLockedHint:
      '当前已锁定「格式检测」范围：只可取消勾选以缩小目标 Sheet，不可勾选未检测类型。变更队列后锁定解除，需重新检测。',
    targetSheetsIngestHint:
      '建议在正式导入前一次性确认目标范围，避免先导部分类型后再扩范围时被“重复文件跳过”影响补导。格式检测通过后再点「开始导入」。选择的目标 Sheet 将参与 Excel→ODS 链路；若任一目标 Sheet 在任一阶段失败，将按所选失败策略处理整份 Excel。开发环境请先运行本地 API（如 dev.bat）。生产打包版若已内置并自动拉起本地 API，则无需手动启动。生产构建下若 API 不可用将提示错误。 （开发提示：开发模式下可自动回退模拟流程（不写 ODS）；打包无 API 演示可设 VITE_IMPORT_SIM_ON_FAIL=true。）',
    failPolicy: '文件或sheet异常则整份Excel不写入',
    failStop: '停下来',
    failSkip: '跳过该 Excel（继续下一个）',
    /** 导入完成后复盘区 */
    resultTitle: '本次导入结果',
    resultSuccess: '成功文件',
    resultFailed: '失败',
    resultSkipped: '跳过',
    resultDownloadJson: '下载 JSON（汇总）',
    resultDownloadCsv: '下载 CSV（拒收行样本）',
    resultRetryFailed: '仅重试失败文件',
    resultDismiss: '关闭',
    resultCsvEmpty: '本次无拒收行样本，CSV 将为仅表头。',
    resultHint: '导入完成后在此复盘；可导出汇总与行级拒收样本，或将失败文件重新加入队列。',
    resultSourceBadgeApi: '执行方式：本地 API（按服务端逻辑写入 ODS，以实际落库为准）。',
    resultSourceBadgeSim: '执行方式：模拟流程（未调用 API，ODS 无写入）。',
    resultSourceBadgeSimFallback:
      '执行方式：因无法连接或未成功调用本地 API，已回退为模拟流程（ODS 无写入）。生产环境请启动 API 后重试；或设置 VITE_IMPORT_SIM_ON_FAIL=true 以允许无 API 演示。',
    placeholderPage: '待开发',
  },

  /** ODS数据查看（开发阶段：仅 ODS 真实数据，无演示兜底） */
  dataPreviewUi: {
    pageTitle: 'ODS数据查看',
    pageBody:
      '按导入批次与会话查看已写入 ODS 的抽样行。Tab 仅展示本批次确有数据的 Sheet 类型；Tab 顺序与标题与 `config/sheet_mapping.yaml` 一致（同 ODS 类型取 YAML 中首次出现的 Sheet 中文名，如「发票基础数据」「汇总信息表」）。请先启动本地 API，并确保已产生导入日志（ods_load_log）。',
    listLoadErrorTitle: '批次列表加载失败',
    refresh: '刷新列表',
    refreshing: '刷新中…',
    bootstrapLoading: '正在从本地 API 加载「ODS数据查看」…',
    emptyCardTitle: '暂无可用批次',
    emptyBody: '当前环境尚无已导入批次。请先在「文件上传」完成导入，或等待接入服务端批次查询接口。',
    ctaUpload: '前往文件上传',
    batchCardTitle: '选择批次 / 导入会话',
    batchSelectLabel: '批次与会话',
    optionFilesOk: '文件成功',
    kpiBatchId: '批次 ID',
    kpiSession: '会话 ID',
    kpiSuccess: '成功 / 总文件',
    kpiFailed: '失败文件',
    kpiAttachments: '附件',
    kpiSource: '落盘目录',
    kpiSourcePathUnknown: '（刷新后从 API 获取；未启动服务或请求失败时可能为空）',
    fileFilterLabel: '来源文件',
    fileFilterAll: '全部来源',
    viewModeLabel: '视图',
    viewModeStd: '标准（字段映射）',
    viewModeRaw: '原始（Excel 列）',
    searchPlaceholder: '搜索任意列（全部单元格内容）…',
    tableCardTitle: '数据表',
    tableNoColumns: '该表类型在本批次无列定义或未落库。',
    tableEmptyNoData: '该表在本批次暂无数据。',
    tableEmptyFilter: '无符合筛选条件的行，请调整搜索关键词。',
    noTabsHint: '本批次暂无带数据的业务表可预览（可能仅含附件或尚未写入明细）。',
    /** Tab 由后端按本会话 parquet 路径中的「表类型=…」聚合，非固定两项 */
    tabsBarHint:
      '表类型 Tab 由**本会话实际落盘的 Parquet**动态决定：有几种表类型即显示几个；标题与顺序与 `config/sheet_mapping.yaml` 中首次出现的 Sheet 名一致。若导入文件未含某类 Sheet，则不会出现对应 Tab。',
    tabsQuickSwitch: '快速切换表类型',
    loadMore: '加载更多',
    loadMoreLoading: '加载中…',
    loadMoreEnd: '已加载当前可预览的全部片段（仍非全量导出）。',
    tableFootnote:
      '本表当前已累积 {n} 行（前端筛选后可见表格行数）。列较多时请横向滚动。数据按游标分页从 ODS Parquet 拉取，每批最多 {cap} 行；可点击「加载更多」继续追加。',
    loadDetailHint: '正在从 ODS 加载本会话明细…',
    apiListEmptyHint: '本地库中暂无导入日志。请先在「文件上传」完成导入，或确认本地 API 与 DuckDB 已就绪后点击刷新。',
    emptyBodyAfterError:
      '请检查：1）本地 API 是否已启动（如 dev.bat api），且工作目录为仓库根目录；2）data/database/warehouse.duckdb 是否被 DBeaver、另一个 Python/Streamlit 进程占用（关闭或结束进程后重试）；3）已安装 duckdb Python 包。刷新后红字错误会附带具体异常类型与原因。',
    footerHint:
      '说明：数据来自于当前 ODS 实例；修改映射或重新导入后，请刷新列表。失败文件请结合「文件上传」导入结果或历史批次记录核对。',
    linkUpload: '返回文件上传',
    linkHistory: '历史批次记录',
    deleteSessionBtn: '删除此导入会话',
    deleteBatchBtn: '删除整个批次',
    deleteSessionSessionsInBatch: '该批次在列表中共有 {n} 条导入会话。',
    deleteDialogSessionTitle: '删除当前导入会话',
    deleteDialogSessionBody:
      '将删除本会话在 ODS 中写入的 Parquet 文件、对应 manifest 以及 `ods_load_log` 中的本条记录。若同一文件路径仍被同批次的其它会话引用，则该文件会被保留。此操作不可恢复。',
    deleteDialogBatchTitle: '删除整个导入批次',
    deleteDialogBatchBody:
      '将删除该批次在 ODS 下的全部目录（`批次=…` 与 `manifests/批次=…`），并清除该批次在 `ods_load_log` 与 `ods_batch_state` 中的全部记录（所有导入会话）。此操作不可恢复。',
    deleteAckCheckbox: '我已知晓上述后果，确认删除',
    deleteConfirmInputLabel: '请输入批次 ID 以确认删除整个批次',
    deleteConfirmInputPlaceholder: '完整复制上方 KPI 中的批次 ID',
    deleteConfirmMismatch: '输入的批次 ID 与当前批次不一致',
    deleteCancel: '取消',
    deleteSubmit: '确认删除',
    deleteBusy: '删除中…',
    deleteErrorPrefix: '删除失败',
  },

  /** 历史批次记录（高保真界面原型：以 ODS 落盘日志聚合展示） */
  importHistoryUi: {
    pageTitle: '历史批次记录',
    pageBody:
      '按导入批次查看历史运行记录（当前阶段以 ODS 落盘日志为准）。可按批次/会话检索、查看会话概览，并从此处进入 ODS数据查看 或执行删除等运维操作。重跑入口先保留外观与交互壳，后续再接入方案 A 的实际重跑逻辑。',
    kpiSource: '数据来源（ODS 根目录）',
    listLoadErrorTitle: '批次列表加载失败',
    listLoadError: '无法加载批次列表',
    refresh: '刷新列表',
    refreshing: '刷新中…',
    ctaUpload: '前往文件上传',
    emptyCardTitle: '暂无历史批次',
    emptyBody: '当前环境尚无已导入批次。请先在「文件上传」完成导入后返回此页刷新。',
    listCardTitle: '批次列表',
    detailCardTitle: '批次详情',
    detailEmpty: '请选择左侧批次查看详情。',
    searchPlaceholder: '搜索批次 ID / 会话 ID…',
    totalHint: '共 {n} 个批次',
    colBatch: '批次 ID',
    colSessions: '会话数',
    colSuccess: '成功/总文件',
    colFailed: '失败文件',
    colWarn: '告警',
    colLastTime: '最近导入',
    kpiBatchId: '批次 ID',
    kpiSessions: '会话数',
    kpiOdsFiles: 'ODS 文件数',
    kpiSuccess: '成功/总文件',
    kpiFailed: '失败文件',
    sessionSelectLabel: '选择会话',
    sessionKpiTitle: '选中会话',
    kpiLoadedAt: '导入时间',
    kpiFilesOk: '成功/总文件',
    kpiParquet: 'Parquet 路径数',
    gotoPreview: '新窗口预览',
    gotoPreviewHint: '在新窗口打开「ODS数据查看」，并自动选中当前批次/会话',
    rerunFailed: '重跑（仅失败）',
    rerunAll: '重跑（全量）',
    rerunSoonHint: '先展示界面与交互壳；后续接入方案 A 的实际重跑逻辑',
    detailFootnote:
      '提示：当前页以 ODS 落盘日志聚合展示，后续可扩展到“格式检测快照 / 失败原因聚合 / ODS→DWD 状态”等。',
    deleteSessionBtn: '删除此会话产物',
    deleteBatchBtn: '删除整个批次',
    deleteDialogSessionTitle: '删除当前导入会话',
    deleteDialogSessionBody:
      '将删除本会话在 ODS 中写入的 Parquet 文件、对应 manifest 以及 `ods_load_log` 中的本条记录。若同一文件路径仍被同批次的其它会话引用，则该文件会被保留。此操作不可恢复。',
    deleteDialogBatchTitle: '删除整个导入批次',
    deleteDialogBatchBody:
      '将删除该批次在 ODS 下的全部目录（`批次=…` 与 `manifests/批次=…`），并清除该批次在 `ods_load_log` 与 `ods_batch_state` 中的全部记录（所有导入会话）。此操作不可恢复。',
    deleteAckCheckbox: '我已知晓上述后果，确认删除',
    deleteConfirmInputLabel: '请输入批次 ID 以确认删除整个批次',
    deleteConfirmInputPlaceholder: '完整复制上方批次 ID',
    deleteConfirmMismatch: '输入的批次 ID 与当前批次不一致',
    deleteNeedAck: '请勾选确认项',
    deleteCancel: '取消',
    deleteSubmit: '确认删除',
    deleteBusy: '删除中…',
    deleteError: '删除失败',
  },

  /** ODS→DWD 处理中心（高保真界面原型：任务中心/控制台视角） */
  odsToDwdCenterUi: {
    pageTitle: 'ODS→DWD',
    pageBody:
      '按批次把已落盘到 ODS 的数据构建到 DWD（清洗、标准化、去重、质量校验）。默认执行「增量构建」：只处理还没写入 DWD 水位的导入会话；「强制重洗」仅用于已有 DWD 水位的会话（先删旧行再重算）。若会话还没有 DWD 水位，请用批量或单次增量构建。详见 `docs/ODS到DWD增量构建与强制重洗.md`。',
    refresh: '刷新列表',
    refreshing: '刷新中…',
    emptyCardTitle: '暂无可处理批次',
    emptyBody: '当前环境尚无已导入批次可用于 DWD 构建。请先在「文件上传」完成导入。',
    filtersCardTitle: '筛选与批次范围',
    searchPlaceholder: '搜索批次 ID…',
    statusAll: '全部状态',
    statusNotBuilt: '未构建',
    statusRunning: '构建中',
    statusSucceeded: '已构建',
    statusFailed: '失败',
    listCardTitle: '批次队列',
    detailCardTitle: '批次详情',
    colBulkExpand: '批量',
    bulkToolbarHint: '勾选批次表示选中该批次下全部导入会话；展开后可只选部分会话。与右侧单次「开始构建」独立。',
    bulkSelectAllFiltered: '全选（当前筛选）',
    bulkClearSelection: '清空选择',
    bulkIncrementalBuild: '批量增量构建',
    bulkIncrementalSummary: '{b} 个批次 · {s} 个会话',
    bulkIncrementalFailPrefix: '批量增量失败：',
    bulkExpandSessions: '展开会话',
    bulkCollapseSessions: '收起',
    colBatch: '批次',
    colOds: 'ODS',
    colDwd: 'DWD',
    colQuality: '质量闸门',
    colUpdated: '更新时间',
    badgeNotBuilt: '未构建',
    badgeRunning: '构建中',
    badgeSucceeded: '已构建',
    badgeFailed: '失败',
    kpiBatchId: '批次 ID',
    kpiOdsFiles: 'ODS 文件数',
    kpiEstRows: 'ODS 导入行数（日志）',
    kpiDwdRows: 'DWD 行数',
    kpiLastRun: '最后构建',
    kpiDuration: '耗时',
    actionsTitle: '操作',
    actionBuild: '开始构建（增量）',
    /** 左侧展开列表标题 */
    bulkExpandedSessionListTitle: '各导入会话（勾选参与批量增量；仅已有 DWD 水位的会话显示「强制重洗」）',
    /** 右侧详情区 */
    detailForceRebuildHint:
      '「强制重洗」仅适用于已完成过增量 DWD（已有水位）的会话；尚未落盘 DWD 的会话请用「批量增量构建」或右侧「开始构建（增量）」。',
    /** 无水位时会话行不展示强制重洗按钮时的说明 */
    forceRebuildUnavailableHint: '该会话尚无 DWD 水位，请先执行增量构建；强制重洗用于覆盖已落盘数据。',
    sessionWatermarkHint: 'DWD 水位',
    forceRebuild: '强制重洗',
    forceRebuildHint: '删除该会话在 DWD 中曾写入的行并重算（需确认）',
    forceRebuildConfirm:
      '将删除该导入会话在 dwd_inv_header / dwd_inv_detail 中的行，并重置 ods_load_log 水位后重跑清洗。此操作不可自动撤销，是否继续？',
    actionRetryFailed: '重跑失败步骤',
    actionRollback: '回滚该批次',
    actionViewLogs: '查看日志',
    actionBuildHint: 'POST /api/dwd/build（默认 incremental=true）；请保持 Local API 已启动',
    actionBuildTitle: '仅处理尚未记录 DWD 水位的会话，将 ODS 写入 dwd_inv_header / dwd_inv_detail',
    actionDisabledHint: '下列能力尚未接入：重跑单步 / 回滚 / 日志文件视图',
    stepperTitle: '流水线步骤',
    steps: {
      readOds: '读取 ODS',
      standardize: '清洗/标准化',
      dedupe: '主键去重',
      enrich: '维度关联',
      writeDwd: '写入 DWD',
      validate: '质量校验',
    },
    panelsTitle: '观测与指标',
    tabLogs: '构建日志',
    tabMetrics: '指标概览',
    logsPlaceholder: '此处展示流水线日志（后续对接后端事件流/日志文件）。',
    logsPrototypeNote:
      '尚未在本页执行「开始构建」时无日志。点击「开始构建（增量）」或「强制重洗」后，此处将显示本次 API 返回的摘要。若列表 DWD 仍为「未构建」，请先完成 Excel→ODS 导入并确保 Local API 可访问 DuckDB。',
    metricsPlaceholder:
      '此处展示质量闸门指标（空值率、重复率、金额校验等）。先做高保真布局，待规则确认后接入计算与落库。',
    metricsPrototypeNote: '说明：下列百分比与数字为布局占位，非真实质检结果。',
  },

  /** 加工中心：DWD数据查看（对齐 ODS数据查看 的批次/会话筛选与运维删除） */
  dwdPreviewUi: {
    pageTitle: 'DWD数据查看',
    pageBody:
      '查看已通过「ODS→DWD」写入 DuckDB 的数据。下方 Tab 与 **ODS 数据查看** 中本批次/本会话的表类型顺序一致，并按 `source_parquet_file` 血缘过滤；仅当该类型在 DWD 中有行时才显示 Tab（当前清洗管线对应 `inv_header`→主表、`inv_detail`→明细）。**删除**仅移除 DWD 行并将 `ods_load_log` 的 DWD 水位置空，不删除 ODS Parquet。',
    refresh: '刷新列表',
    refreshing: '加载中…',
    emptyListTitle: '暂无导入批次',
    emptyListBody: '请先在「文件上传」完成导入，并在「ODS→DWD」中构建 DWD。',
    batchCardTitle: '选择批次 / 导入会话',
    filterCardTitle: '表类型（对齐 ODS）与数据加载',
    tabsLoading: '正在同步 ODS 表类型…',
    noTabsHint:
      '当前批次/范围下没有可展示的 DWD Tab（可能尚未构建、无匹配血缘，或 ODS 路径中未出现 inv_header / inv_detail）。可先刷新列表或到「ODS→DWD」构建。',
    labelBatch: '导入批次',
    labelSession: '导入会话',
    sessionAll: '整批（全部会话）',
    layerHeader: '主表 dwd_inv_header',
    layerDetail: '明细 dwd_inv_detail',
    loadFirstPage: '加载数据',
    loadMore: '加载更多',
    loadAll: '全部加载',
    loadAllHint:
      '按接口单次最多 500 行连续拉取，直至无更多或达到上限（{max} 行）；便于在浏览器内全文/按列筛选。超大数据集请改用导出或专用查询。',
    loadAllCapped: '已达到单次「全部加载」上限 {max} 行，已暂停。可继续点击「加载更多」分段拉取。',
    alreadyFullyLoaded: '当前 Tab 下数据已全部在浏览器中。',
    loading: '读取中…',
    totalRows: '本筛选约 {n} 行',
    totalUnknown: '行数统计不可用',
    noRows: '当前筛选下无 DWD 行（可能尚未构建或会话不匹配）。',
    tableHint: '列较多时可横向滚动；值为空表示 NULL。',
    searchLabelFulltext: '全文',
    searchPlaceholder: '在已加载数据中搜索（匹配任意列）…',
    columnFilterTitle: '按列筛选',
    /** 单行工具条内与「全文」并列时的短标签 */
    columnFilterInline: '按列',
    columnPick: '列',
    columnContains: '包含',
    addColumnFilter: '添加条件',
    clearFilters: '清除筛选',
    filterChipRemove: '移除此条件',
    filteredCount:
      '已加载 {loaded} 行 · 筛选后 {shown} 行',
    filterNoMatch: '当前条件下无匹配行，可调整关键字/列条件，或先「加载更多」扩大已加载范围。',
    searchScopeNote:
      '说明：筛选仅在当前已加载到浏览器的行内生效；未分页加载的数据不会参与匹配。',
    apiHint: 'GET /api/dwd-preview/tabs · GET /api/dwd-preview/table-page · POST /api/dwd-preview/delete',
    kpiBatchId: '批次 ID',
    kpiSession: '会话',
    kpiDwdHeader: 'DWD 主表行（本会话/合计）',
    kpiDwdDetail: 'DWD 明细行（本会话/合计）',
    kpiDwdWatermark: 'DWD 水位',
    watermarkNone: '未构建',
    deleteSessionBtn: '删除本会话 DWD 落库',
    deleteBatchBtn: '删除本批次 DWD 落库',
    deleteSessionSessionsInBatch: '该批次在列表中共有 {n} 条导入会话。',
    deleteSessionNeedPick:
      '请先在下拉框中选择**某一导入会话**（勿选「整批」）后再删除本会话 DWD 落库。',
    deleteDialogSessionTitle: '删除当前导入会话的 DWD 落库',
    deleteDialogSessionBody:
      '将删除该会话在 `dwd_inv_header` / `dwd_inv_detail` 中 `import_batch_id`+`import_session_id` 匹配的全部行，并把 `ods_load_log.dwd_session_processed_at` 置空。**不会**删除 ODS Parquet。删除后可至「ODS→DWD」重新增量构建。',
    deleteDialogBatchTitle: '删除整个导入批次的 DWD 落库',
    deleteDialogBatchBody:
      '将删除该**批次 ID** 下全部会话写入的 DWD 行，并把该批次所有会话的 DWD 水位置空。**不会**删除 ODS 目录与 Parquet。删除后可至「ODS→DWD」重新增量构建。',
    deleteConfirmInputLabel: '请输入批次 ID 以确认删除整批 DWD',
    deleteConfirmInputPlaceholder: '完整复制上方 KPI 中的批次 ID',
    deleteConfirmMismatch: '输入的批次 ID 与当前批次不一致',
    deleteAckCheckbox: '我已知晓上述后果，确认删除 DWD 落库数据',
    deleteNeedAck: '请勾选确认项',
    deleteCancel: '取消',
    deleteSubmit: '确认删除',
    deleteBusy: '删除中…',
    deleteErrorPrefix: '删除失败',
    footerHint:
      '说明：与「ODS数据查看」中删除 ODS 不同，此处仅清理 DuckDB 中 DWD 层数据；ODS 文件仍保留，需重新构建时请使用加工中心「ODS→DWD」。',
    linkOdsToDwd: '前往 ODS→DWD',
    linkOdsPreview: '前往 ODS数据查看',
  },

  uploadZone: {
    primaryLine: '拖放 Excel 文件或文件夹到此处',
    actionHint: '或点击：',
    /** 虚线区默认行为为打开文件夹选择；内联「选择文件」仍可单选/多选文件 */
    ariaMainAction: '选择文件夹（拖拽或点此区域）；内文链接可改为选择文件',
    pickFiles: '选择文件',
    pickFolder: '选择文件夹',
    helperDefault:
      '建议 Excel 命名：{公司简称}_{进项/销项}_年度（或X月至Y月）.xlsx。选文件夹时会自动忽略打开表格产生的 ~$ 锁文件（非真实工作簿）。',
  },
} as const

export type ZhCN = typeof zhCN
