/**
 * 中文界面文案集中定义（单文件，便于业务侧「像改配置一样」调整措辞）。
 * 新增页面/菜单时：先在此补充字段，再在组件中引用 `zhCN.xxx`，避免散落硬编码。
 *
 * 文件上传页（示例）：
 * - 页标题、页内说明、批次配置、队列、按钮等 → `importUpload`
 * - 虚线拖拽区主文案、选文件/选文件夹、命名说明 → `uploadZone`
 */
export const zhCN = {
  common: {
    soon: '待开发',
    /** 已立项/可进入，功能迭代中 */
    inProgress: '开发中',
    logout: '退出',
    help: '帮助',
  },

  login: {
    brandSub: '票鉴 · 发票大数据审计分析',
    sep: '请登录后继续',
    /** Phase 1 演示用；接入 FastAPI 后由服务端校验与返回用户信息 */
    /** 当前为便于验证：账号、密码均为空字符串时视为演示登录通过 */
    demoUsername: '',
    demoPassword: '',
    demoTip:
      '演示：账号与密码均留空即可登录（Phase 1 原型）。填写任意内容将按错误账号处理。',
    /** 避免与浏览器自动填充冲突时的一键入口 */
    demoOneClick: '免填账号，直接登录',
    demoDisplayName: '管理员',
    demoRole: '管理员',
    accountLabel: '账号',
    passwordLabel: '密码',
    accountPlaceholder: '请输入账号',
    passwordPlaceholder: '请输入密码',
    remember: '记住我',
    forgotPassword: '忘记密码',
    submit: '登录',
    footnote: '本地离线运行 · 权限与审计留痕用于控制危险操作',
    errorInvalid: '账号或密码错误',
  },

  shell: {
    /** 产品英文名（Logo、alt、部分标题） */
    appNameEn: 'InvoiceLens',
    /** 浏览器标签页标题（与 `index.html` 默认 title 保持一致，运行时在入口同步） */
    documentTitle: 'InvoiceLens · 票鉴',
    sidebarCollapseTitle: '收起/展开侧边栏',
    brandSub: '票鉴 · 发票大数据分析工具',
    licenseTag: '专业版 · 有效期 2025-12-31',
  },

  sidebar: {
    sectionPrep: '数据准备',
    sectionAnalysis: '分析看板',
    sectionOutput: '输出',
    sectionSystem: '系统',
    invoiceData: '发票数据',
    fieldMapping: '字段映射配置',
    mappingConfig: 'ODS层映射配置',
    mappingTemplates: '模板管理',
    importWizard: '发票导入向导',
    fileUpload: '文件上传',
    dataPreview: 'ODS数据查看',
    formatCheck: '格式检测',
    processingCenter: '加工中心',
    odsToDwd: 'ODS→DWD',
    dwdToDim: 'DWD→DIM',
    dwdDataPreview: 'DWD数据查看',
    processingDerivedDimTasks: 'DWD派生任务',
    historyBatches: '历史批次记录',
    qualityReport: '数据质量报告',
    qualityOverview: '质量概览',
    qualityDetail: '异常明细',
    qualityTrend: '质量趋势',
    invoiceExport: '发票数据导出',
    dimMgmt: '维度管理',
    badgeNew: '新',
    dimOrg: '企业组织维度',
    dimEnterpriseLibrary: '主体库',
    dimVersion: '年度口径版本',
    dimAuditRelatedLibrary: '发票报送覆盖分析',
    dimLevel1EnterpriseYear: '年度一级企业名单',
    dimAuditedEnterprise: '被审企业组织',
    dimAuditedLedger: '管理与产权层级信息',
    dimAuditedContribution: '出资与参股情况',
    dimOrgTree: '管理关系树',
    dimEquityTree: '产权关系树',
    dimOrgDiff: '管产关系视图',
    dimInvoiceLink: '企业→票（主体映射）',
    dimTaxCode: '税收分类编码',
    dimTaxLib: '编码库管理',
    dimTaxRiskDefine: '敏感类目定义',
    dimTaxResult: '税收分类层级树',
    dimTaxQuality: '关联质量',
    taxAnalysis: '税务分析',
    taxEnterpriseStructure: '税收分类结构',
    taxInOutDeviation: '进销偏离分析',
    taxRiskExposure: '风险暴露分析',
    dimDict: '数据字典维护',
    dimSubjectCategory: '主体类别',
    overview: '数据概览',
    ovSummary: '整体汇总',
    ovTrend: '月度趋势',
    ovTax: '税率结构',
    healthScore: '被审企业健康度评价',
    supplier: '供应商分析',
    supplierCr: '集中度（CR值）',
    supplierTop: 'Top 供应商明细',
    supplierNew: '新增/消失供应商',
    flags: '审计疑点',
    flagsList: '疑点清单',
    flagsRules: '规则配置',
    flagsTrack: '疑点跟踪',
    related: '关联交易',
    relatedGraph: '图谱分析',
    relatedPairs: '对开发票',
    relatedShell: '通道公司识别',
    finance: '财务校验',
    financeReconcile: '发票与账表核对',
    financeDiff: '差异分析',
    compare: '子公司对比',
    compareRank: '评级排名',
    compareCharts: '横向对比图表',
    report: '生成报告',
    reportConfig: '报告配置',
    reportTemplates: '报告模板管理',
    reportArchive: '历史报告存档',
    users: '用户管理',
    usersList: '用户列表',
    usersRoles: '角色权限配置',
    usersAudit: '操作日志',
    settings: '系统设置',
    settingsThresholds: '规则阈值',
    settingsLicense: '授权管理',
    settingsInstance: '实例配置',
  },

  breadcrumb: {
    invoiceData: '发票数据',
    importWizard: '发票导入向导',
    fileUpload: '文件上传',
    formatCheck: '格式检测',
    dataPreview: 'ODS数据查看',
    processingCenter: '加工中心',
    odsToDwd: 'ODS→DWD',
    dwdToDim: 'DWD→DIM',
    dwdDataPreview: 'DWD数据查看',
    processingDerivedDimTasks: 'DWD派生任务',
    historyBatches: '历史批次记录',
    fieldMapping: '字段映射配置',
    mappingConfig: 'ODS层映射配置',
    mappingTemplates: '模板管理',
    pending: '待开发',
    /** 数据质量报告（高保真原型导航） */
    qualityReport: '数据质量报告',
    qualityOverview: '质量概览',
    qualityDetail: '异常明细',
    qualityTrend: '质量趋势',
    healthScore: '被审企业健康度评价',
    dimEnterpriseLibrary: '主体库',
    dimAuditRelatedLibrary: '发票报送覆盖分析',
    dimLevel1EnterpriseYear: '年度一级企业名单',
    dimAuditedLedger: '管理与产权层级信息',
    dimAuditedContribution: '出资与参股情况',
    dimOrgTree: '管理关系树',
    dimEquityTree: '产权关系树',
    dimOrgDiff: '管产关系视图',
    dimInvoiceLink: '企业→票（主体映射）',
    dimVersion: '年度口径版本',
    dimTaxCodeSection: '税收分类编码',
    dimTaxLib: '编码库管理',
    dimTaxRiskDefine: '敏感类目定义',
    dimTaxResult: '税收分类层级树',
    dimTaxQuality: '关联质量',
    dimSubjectCategory: '主体类别',
    taxEnterpriseStructure: '税收分类结构',
  },

  /**
   * 字段映射配置（高保真原型 → 后续对接 API / 写回 YAML）
   */
  fieldMappingUi: {
    prototypeBadge: '界面原型',
    sourceLive: '已接通',
    sourceOffline: '离线',
    sourceLabelPrefix: '来源：',
    loadFromApiFailed: '无法从本地 API 加载字段映射，已显示内置兜底配置。',
    apiUnavailableHint:
      '说明：该能力已实现。开发模式（npm run dev）下默认通过 Vite 将「同源 /api」代理到 127.0.0.1:8765。日常请在仓库根目录双击 dev.bat（单窗口同时起 API 与 Vite）；若仅用 npm run dev，须另开 dev.bat api。若仍失败：检查 8765、防火墙；或在前端 .env 设置 VITE_LOCAL_API_BASE 直连。',
    refreshFailed: '从服务器刷新失败。',
    saveSuccess: '已保存到 field_mapping.yaml。',
    saveSuccessWithPath: '已保存：{path}',
    saveFailed: '保存失败',
    busyLoading: '加载中…',
    busySaving: '保存中…',
    saveTooltip: '将当前编辑写回 config/field_mapping.yaml（会先备份 .bak）',
    saveDisabledNoChanges: '没有未保存的修改',
    configPageTitle: 'ODS层映射配置',
    configPageBody:
      '维护「标准字段（建议与 ODS 列名一致）↔ 业务含义（label_zh）与表头别名（aliases）」对照关系，供格式检测与 Excel→ODS 使用。打开本页会从本地 API 拉取 config/field_mapping.yaml；可编辑已有字段，在「全局默认」下可用「添加字段」；在「按 Sheet 类型」下还可使用「表头检测」对照样例 Excel 补键。保存后写回磁盘并保留 sheet_header_slugs 等未编辑块。',
    configYamlHint:
      '配置文件路径：项目根目录 config/field_mapping.yaml。修改后可在「文件上传」页使用「刷新映射」或重启本地 API 使前端加载最新定义。',
    configOdsDwdHint:
      '设计建议：ODS 层字段命名尽量稳定、语义清晰，后续 DWD 可在同义列上叠加清洗规则（如丢弃「序号」、补充维度外键），避免在 DWD 再猜 Excel 原始表头。',
    toolsBatchHint:
      '批量从样本目录归纳字段可运行：python tools/generate_field_mapping_from_samples.py（详见仓库 README）。',
    contextCardTitle: '配置上下文',
    modeGlobal: '全局默认',
    modeSheet: '按 Sheet 类型',
    modeGlobalHint: '适用于多数票种的默认块；未单独覆盖的 Sheet 类型将回退到此处定义。',
    sheetPickLabel: '选择 Sheet 类型',
    sheetHasOverride: '已有 YAML 独立块',
    gotoUpload: '前往文件上传（验证映射）',
    tableCardTitle: '字段对照表',
    globalCoverageHint:
      '「表头检测」需对照具体样例表：请切换到「按 Sheet 类型」并选定目标 Sheet 后使用。若要把检出列一并写入全局 default，可在导入时选择「当前 Sheet + 全局 default」。',
    sheetContextBanner:
      '当前编辑 Sheet：{name}。仅列出 YAML 中该子块已声明的字段；灰色占位为全局 default 原文（未写入本 Sheet 时生效）。本块有填写则以本块为准。',
    sheetNoBlockRows: '当前 YAML 中尚无该 Sheet 的 `sheets` 子块，或块内无字段；请先在其他工具中生成块，或切换到「全局默认」编辑。',
    searchPlaceholder: '搜索字段 key / 中文名 / 别名…',
    tableSearchNoMatch: '没有符合搜索条件的行。',
    refreshFromServer: '从服务器刷新',
    refreshTooltip: '调用本地 API 重新加载 field_mapping.yaml',
    saveToYaml: '保存到配置',
    saveDisabledTooltip: '没有可保存的修改',
    colOds: 'ODS 标准字段',
    colZhTitle: '业务含义',
    colAliases: '表头别名（多值）',
    colType: '类型',
    colMatch: '匹配',
    colStatus: '状态',
    valueType: {
      string: '文本',
      date: '日期',
      amount: '金额',
    },
    matchMode: {
      /** 与运行时一致：先整表头归一化后与别名等价，否则列名归一化后包含别名子串 */
      exact: '归一化等价',
      contains: '等价或包含',
    },
    requiredTag: '必填',
    statusAligned: '已对齐',
    statusReview: '待复核',
    statusModified: '已修改',
    statusEditing: '编辑中',
    tableFootnote:
      '按 Sheet 编辑时灰色占位为全局 default 原文；本块有 label_zh / aliases 则以本块为准。别名多行、失焦按行解析写回。',
    addFieldToggle: '添加字段',
    addFieldTitle: '新增标准字段',
    addFieldOdsLabel: 'ODS 字段名（蛇形）',
    addFieldOdsPlaceholder: '例如 buyer_email',
    addFieldZhLabel: '业务含义（label_zh）',
    addFieldAliasesLabel: '表头别名（每行一条，可选）',
    addFieldAlsoDefault: '同时写入全局 default',
    addFieldSubmit: '加入当前上下文',
    addFieldCancel: '收起',
    addFieldErr: {
      empty: '请填写 ODS 字段名。',
      invalid: '须为小写蛇形：以小写字母开头，仅含 a–z、0–9、下划线。',
      long: 'ODS 字段名过长。',
      duplicate: '该字段在当前上下文中已存在。',
      duplicateDefault: '全局 default 中已存在该字段名。',
      duplicateSheet: '当前 Sheet 子块中已存在该字段名。',
      needContent: '请至少填写业务含义或一条别名（可仅填业务含义，将同时作为一条别名）。',
    },
    addFieldAlsoDefaultHint:
      '勾选后：完整定义只写入全局 default；当前 Sheet 仅增加「引用 default」的空项（aliases 为空）。',
    coverageToggle: '表头检测（未覆盖列）',
    coverageTitle: '上传样例 .xlsx，列出 YAML 未覆盖的表头并建议英文 key',
    coveragePickFile: '选择 Excel 文件',
    coverageRunning: '检测中…',
    coverageFailed: '检测失败，请确认已启动本地 API 且文件为 .xlsx。',
    coverageEmpty: '未检出未覆盖表头（或所选目标 Sheet 与文件不匹配）。',
    coverageHint: '检出 {n} 条未覆盖列，可选中后导入。',
    coverageSheetCol: '工作表',
    coverageHeaderCol: '表头原文',
    coverageSlugCol: '建议 key（可改）',
    coverageImportTo: '导入到：',
    coverageImportGlobal: '仅全局 default',
    coverageImportSheet: '当前 Sheet 子块',
    coverageImportSheetAndDefault: '当前 Sheet + 全局 default',
    coverageSelectAll: '全选',
    coverageSelectNone: '全不选',
    coverageApply: '导入选中项',
    coverageAlsoNote:
      '选「当前 Sheet + 全局 default」时：若当前 Sheet 对该 key 已有本地 label/别名，则只在 Sheet 中合并；若 Sheet 无本地值（含仅空继承）而 default 已有该 key，则只在 default 中合并；若二者均无该 key 的有效定义，则只在 Sheet 中合并写入。',
    coverageImported: '已合并到当前编辑（未自动保存，请点「保存到配置」）。',
    coverageAbortedInvalidKeys: '存在不合法的英文 key，已取消本批导入，未修改任何数据。',
    addFieldSuccess: '已加入当前编辑（未自动保存）。',
    templatesPageTitle: '模板管理',
    templatesPageBody:
      '管理「样例 Excel 包、列说明、校验规则片段」等可复用资产，便于新项目或新票种快速对齐字段映射。以下为占位卡片，用于评审信息架构与操作动线。',
    templatesInfoBanner:
      '模板与 ODS 层映射的关系：模板提供「样例数据 + 推荐字段清单」，导入「ODS层映射配置」后参与格式检测；不会替代 field_mapping.yaml 作为运行时真源。',
    templateActionSoon: '下一阶段开放',
    downloadSample: '下载样例包',
    applyTemplate: '应用到当前环境',
    uploadPackTitle: '上传自定义模板包',
    uploadPackDesc: '支持 .zip（含样例 xlsx + README + 可选 mapping 片段）。原型阶段仅展示区域。',
    uploadPackPlaceholder: '将模板包拖拽到此处，或点击选择文件（未接通）',
    templateCards: [
      {
        id: 'golden-vat',
        title: '金税增值税发票 · 标准进项',
        desc: '含「发票基础信息 / 信息汇总表」常见列，适用于多数一般纳税人导出格式。',
        scope: '适用：进项 · 金税三/四期',
        version: '版本 1.2',
        updated: '更新：2026-Q1',
      },
      {
        id: 'rail-eticket',
        title: '铁路电子客票 · 扩展块',
        desc: '补充「日期 / 开票日期」等易混列名与金额类字段，与 field_mapping.yaml 中铁路块对应。',
        scope: '适用：铁路电子客票 Sheet',
        version: '版本 0.9',
        updated: '更新：草案',
      },
      {
        id: 'goods-list',
        title: '货物清单 · 明细行',
        desc: '行级明细与汇总表混合场景下的推荐别名集合（占位）。',
        scope: '适用：货物清单',
        version: '版本 0.6',
        updated: '更新：草案',
      },
    ],
  },

  importUpload: {
    title: '文件上传',
    description:
      '将各级企业从金税系统导出的进项与销项发票数据（Excel 文件）加入队列后，请先进行「格式检测」初筛，通过后再「开始导入」写入 ODS；支持金税三期/四期常见格式。',
    batchConfig: '批次配置',
    labelBatchDate: '批次基准日期',
    batchDatePlaceholder: 'YYYYMMDD',
    batchDateHint: '8 位数字，默认当日；将作为导入批次标识（batch_id）提交。',
    labelMaxFileMb: '单文件大小上限（MB）',
    hintMaxFileMb:
      '格式检测与上传均使用该上限；实际生效为「此处数值」与「服务端 INVOICELENS_MAX_UPLOAD_MB」的较小值（当前服务端硬顶 {mb} MB）。参数保存在本浏览器。',
    labelAutoImportAfterFormat: '格式检测后导入ODS',
    optAutoTrigger: '自动触发',
    optManualTrigger: '手动触发',
    labelForceReimport: '重复文件处理',
    forceReimportToggle: '强制重导（忽略判重）',
    hintForceReimport:
      '开启后将忽略“同一文件哈希已成功导入”的判重保护，适用于扩范围补导或修复历史批次。',
    forceReimportWarn:
      '已开启强制重导：本次将忽略重复文件判定，可能写入重复数据。建议使用新批次并在导入备注中记录原因。',
    // 当前阶段 Excel->ODS 不做进/销分流；该选项仅用于后续 DW 阶段区分/标记
    labelDirection: '后续区分标记',
    labelDwd: '完成后 DWD 清洗',
    optDirAuto: '自动识别（后续区分）',
    optDirIn: '强制进项标记（后续区分）',
    optDirOut: '强制销项标记（后续区分）',
    optDwdAuto: '自动触发',
    optDwdManual: '手动触发',
    hintDwdAuto:
      'ODS 落盘成功后自动对该会话做增量 DWD；可在下方勾选同时重算集团成员购销标志（dim_enterprise_year_rel）。',
    rebuildRelAfterDwdLabel: 'DWD 后重算购销标志',
    rebuildRelAfterDwdHint: '依赖「完成后 DWD」为自动；与加工中心 / ODS→DWD 勾选口径一致（集团台账成员）。',
    importEventPostDwdBegin: '导入后 DWD 构建开始',
    importEventPostDwdEndOk: '导入后 DWD 构建完成',
    importEventPostDwdEndFail: '导入后 DWD 构建失败',
    queue: '当前队列',
    queueEmpty: '暂无文件，请拖拽或点击上传。',
    queueSelectAll: '全选',
    queueRemoveSelected: '移除所选',
    queueRemoveRow: '移除',
    queueRemoveRowTitle: '从队列移除，导入时将跳过该文件',
    pendingImport: '待导入',
    pathNotProvidedHint:
      '出于安全策略，网页无法读取带盘符的绝对路径（如 C:\\…）。使用「选择文件夹」或拖入文件夹时，仅能显示相对路径（相对您所选的那一层文件夹，相当于该批次的「虚拟根」）。',
    pathPlaceholder: '—',
    formatCheck: '格式检测',
    formatCheckPageTitle: '格式检测',
    formatCheckPageBody:
      '在此选文件、勾选目标 Sheet 并执行检测（与上传页同一套规则）：结构/标准字段与 YAML 未覆盖表头分块展示。可在导入前单独完善 field_mapping.yaml；检测通过后可直接进入「文件上传」补批次与失败策略，上传页将视为已通过检测，无需再跑一遍。',
    formatCheckPageCta: '前往文件上传（不携带队列）',
    formatCheckGoUploadPassed: '转至文件上传（已检测通过，上传页不再重复检测）',
    formatCheckParamsCard: '检测参数（单文件上限与目标 Sheet）',
    /** Sheet 覆盖分析子功能（格式检测独立页） */
    sheetCoverageCardTitle: 'Sheet 覆盖分析（子功能）',
    sheetCoverageCardDesc:
      '按 config/sheet_mapping.yaml（与侧栏「刷新映射」一致）中的类型 key，对队列内每个工作簿扫描全部工作表标签：汇总「类型 → 实际出现的表名」，并列出「任一 key 都匹配不到」的物理工作表，便于判断 YAML 是否需补充。',
    sheetCoverageScanButton: '扫描当前队列中的工作表',
    sheetCoverageScanning: '扫描中…',
    /** Sheet 覆盖扫描逐文件进度 */
    sheetCoverageScanningWithProgress: '扫描中 {done}/{total}',
    sheetCoverageNeedQueue: '请先加入至少一个 Excel 文件。',
    sheetCoverageByType: '已知类型（YAML / sheet_mapping）与实际工作表名',
    sheetCoverageMultiMatchHint:
      '同一物理表名可能出现在多行：工作表标签同时命中多个类型 key 的「包含」规则时，与导入链路的表类型判定一致。',
    sheetCoverageColType: '类型 key',
    sheetCoverageColActual: '本队列中出现的实际工作表名（去重）',
    sheetCoverageNoHitInQueue: '（本队列未出现命中该类型的表）',
    /** 已知类型表在隐藏「未命中」行后，若整表无数据时的占位说明 */
    sheetCoverageByTypeEmpty: '本队列中暂无工作表命中已列出的类型 key（相对 sheet_mapping 表名规则）。',
    sheetCoverageUnmapped: '未涵盖在已知类型中的工作表',
    sheetCoverageAllMapped: '当前队列中，所有工作表均至少命中一个已知类型 key。',
    sheetCoverageUnmappedHint:
      '下列工作表名与当前 sheet_mapping 中的任一类型 key 均无法按「表名包含 key」规则匹配。若业务上需要导入这些表，请在 config/sheet_mapping.yaml 等配置中补充类型或调整匹配键。',
    sheetCoveragePerFileDetail: '每个 Excel 里有哪些工作表（逐文件展开）',
    sheetCoveragePerFileDetailIntro:
      '上面的表是「整队列汇总」；这里是「按文件拆开」：逐个文件列出工作簿内全部工作表名。若上面有「未涵盖在已知类型中的工作表」，可在此对照是哪一个文件、哪一张表，便于改 config/sheet_mapping.yaml 或检查金税导出是否缺表。',
    sheetCoverageSheetsInBook: '工作簿内全部工作表',
    sheetCoverageUnmatchedInThisFile: '本文件中未命中已知类型的表',
    formatPassedFromHandoff: '已由「格式检测」页通过校验带入本页，可直接补充批次等信息后「开始导入」，无需再次点击「格式检测」。若修改队列、目标 Sheet、单文件上限或 ODS 层映射配置，将需重新检测。',
    formatChecking: '检测中',
    /** 格式检测逐文件进度：已完成数 / 队列总数 */
    formatCheckingWithProgress: '检测中 {done}/{total}',
    formatPassed: '已通过格式检测，可开始导入。',
    formatFailed: '格式检测未通过，请修正后重新检测。',
    /** 与「YAML 未覆盖表头」分块展示 */
    formatCheckBlockStructure: '结构 / 标准字段问题',
    formatCheckBlockYaml: 'YAML 未覆盖表头（ODS层映射配置）',
    formatCheckYamlHelp:
      '可将表头与建议英文 key 写入 config/field_mapping.yaml 的 sheet_header_slugs，或对样例目录运行 tools/sync_sheet_block_from_samples.py。',
    formatIdleHint:
      '加入文件并勾选目标 Sheet 后，请先点击「格式检测」。.xlsx 将校验：① 必有「发票基础信息」且「信息汇总表/货物清单」至少其一；② 勾选目标对应表的表头是否缺标准字段（对齐 config/field_mapping.yaml，可编辑）。',
    startImport: '开始导入',
    startImportNeedFormat: '请先通过格式检测',
    /** 已通过检测但目标 Sheet 与检测时不一致（或超出已检测范围） */
    startImportTargetSheetsDrift:
      '目标 Sheet 与最近一次格式检测通过时不一致，或包含未检测类型。请重新勾选并执行格式检测后再导入。',
    pause: '暂停',
    importStop: '停止',
    importStopHint: '请求停止拉取事件流（已提交至服务端的任务仍可能继续执行，请在 ODS 批次页核对）',
    importProgress: '导入进度',
    importFailures: '失败记录',
    resumeImport: '继续导入',
    importingNow: '导入中…',
    importPhaseUpload: '正在上传文件 {cur}/{total}…',
    importPhaseProcessing: '上传完成，正在执行导入…',
    importRunErrorTitle: '导入未能完成',
    importEventsStreamError: '未能正常拉取导入事件流，请确认本地 API 仍在运行后重试；必要时查看服务端日志或在「ODS 批次与会话」核对是否已部分落库。',
    importNoSessionEnd: '未收到会话结束事件，无法汇总结果。请查看服务端日志或在「ODS 批次与会话」核对。',
    importFailuresEmpty: '暂无失败记录',
    failureActionStop: '停下来',
    failureActionSkip: '跳过该 Excel',
    targetSheets: '目标 Sheet 范围（Excel→ODS）',
    targetSheetsSelectAll: '全选',
    /** 有格式检测范围锁时「全选」按钮的说明 */
    targetSheetsSelectAllWithinFormatScope: '仅勾选最近一次格式检测所允许的类型（与「转至文件上传」带入的范围一致），不含未检测项。',
    targetSheetsClearAll: '清空',
    targetSheetsRefresh: '刷新映射',
    /** 目标 Sheet 勾选框禁用时的 title */
    targetSheetLockedNotInFormatScope:
      '该类型未包含在最近一次通过的格式检测范围内。请返回「格式检测」页勾选并检测，或在本页变更队列后重新执行格式检测。',
    /** 有范围锁时显示在勾选区下方的提示条 */
    targetSheetsScopeLockedHint:
      '当前已锁定「格式检测」范围：只可取消勾选以缩小目标 Sheet，不可勾选未检测类型。变更队列后锁定解除，需重新检测。',
    targetSheetsIngestHint:
      '建议在正式导入前一次性确认目标范围，避免先导部分类型后再扩范围时被“重复文件跳过”影响补导。格式检测通过后再点「开始导入」。选择的目标 Sheet 将参与 Excel→ODS 链路；若任一目标 Sheet 在任一阶段失败，将按所选失败策略处理整份 Excel。开发环境请先运行本地 API（如 dev.bat）。生产打包版若已内置并自动拉起本地 API，则无需手动启动。生产构建下若 API 不可用将提示错误。 （开发提示：开发模式下可自动回退模拟流程（不写 ODS）；打包无 API 演示可设 VITE_IMPORT_SIM_ON_FAIL=true。）',
    failPolicy: '文件或sheet异常则整份Excel不写入',
    failStop: '停下来',
    failSkip: '跳过该 Excel（继续下一个）',
    /** 导入完成后复盘区 */
    resultTitle: '本次导入结果',
    resultSuccess: '成功文件',
    resultFailed: '失败',
    resultSkipped: '跳过',
    resultDownloadJson: '下载 JSON（汇总）',
    resultDownloadCsv: '下载 CSV（拒收行样本）',
    resultRetryFailed: '仅重试失败文件',
    resultDismiss: '关闭',
    resultCsvEmpty: '本次无拒收行样本，CSV 将为仅表头。',
    resultHint: '导入完成后在此复盘；可导出汇总与行级拒收样本，或将失败文件重新加入队列。',
    resultSourceBadgeApi: '执行方式：本地 API（按服务端逻辑写入 ODS，以实际落库为准）。',
    resultSourceBadgeSim: '执行方式：模拟流程（未调用 API，ODS 无写入）。',
    resultSourceBadgeSimFallback:
      '执行方式：因无法连接或未成功调用本地 API，已回退为模拟流程（ODS 无写入）。生产环境请启动 API 后重试；或设置 VITE_IMPORT_SIM_ON_FAIL=true 以允许无 API 演示。',
    placeholderPage: '待开发',
  },

  /** ODS数据查看（开发阶段：仅 ODS 真实数据，无演示兜底） */
  dataPreviewUi: {
    pageTitle: 'ODS数据查看',
    pageBody:
      '按导入批次与会话查看已写入 ODS 的抽样行。Tab 仅展示本批次确有数据的 Sheet 类型；Tab 顺序与标题与 `config/sheet_mapping.yaml` 一致（同 ODS 类型取 YAML 中首次出现的 Sheet 中文名，如「发票基础数据」「汇总信息表」）。请先启动本地 API，并确保已产生导入日志（ods_load_log）。',
    listLoadErrorTitle: '批次列表加载失败',
    refresh: '刷新列表',
    refreshing: '刷新中…',
    bootstrapLoading: '正在从本地 API 加载「ODS数据查看」…',
    emptyCardTitle: '暂无可用批次',
    emptyBody: '当前环境尚无已导入批次。请先在「文件上传」完成导入，或等待接入服务端批次查询接口。',
    ctaUpload: '前往文件上传',
    batchCardTitle: '选择批次 / 导入会话',
    batchSelectLabel: '批次与会话',
    optionFilesOk: '文件成功',
    kpiBatchId: '批次 ID',
    kpiSession: '会话 ID',
    kpiSuccess: '成功 / 总文件',
    kpiFailed: '失败文件',
    kpiAttachments: '附件',
    kpiSource: '落盘目录',
    kpiSourcePathUnknown: '（刷新后从 API 获取；未启动服务或请求失败时可能为空）',
    fileFilterLabel: '来源文件',
    fileFilterAll: '全部来源',
    viewModeLabel: '视图',
    viewModeStd: '标准（字段映射）',
    viewModeRaw: '原始（Excel 列）',
    searchPlaceholder: '搜索任意列（全部单元格内容）…',
    tableCardTitle: '数据表',
    tableNoColumns: '该表类型在本批次无列定义或未落库。',
    tableEmptyNoData: '该表在本批次暂无数据。',
    tableEmptyFilter: '无符合筛选条件的行，请调整搜索关键词。',
    noTabsHint: '本批次暂无带数据的业务表可预览（可能仅含附件或尚未写入明细）。',
    /** Tab 由后端按本会话 parquet 路径中的「表类型=…」聚合，非固定两项 */
    tabsBarHint:
      '表类型 Tab 由**本会话实际落盘的 Parquet**动态决定：有几种表类型即显示几个；标题与顺序与 `config/sheet_mapping.yaml` 中首次出现的 Sheet 名一致。若导入文件未含某类 Sheet，则不会出现对应 Tab。',
    tabsQuickSwitch: '快速切换表类型',
    loadMore: '加载更多',
    loadMoreLoading: '加载中…',
    loadMoreEnd: '已加载当前可预览的全部片段（仍非全量导出）。',
    tableFootnote:
      '本表当前已累积 {n} 行（前端筛选后可见表格行数）。列较多时请横向滚动。数据按游标分页从 ODS Parquet 拉取，每批最多 {cap} 行；可点击「加载更多」继续追加。',
    loadDetailHint: '正在从 ODS 加载本会话明细…',
    apiListEmptyHint: '本地库中暂无导入日志。请先在「文件上传」完成导入，或确认本地 API 与 DuckDB 已就绪后点击刷新。',
    emptyBodyAfterError:
      '请检查：1）本地 API 是否已启动（如 dev.bat api），且工作目录为仓库根目录；2）data/database/warehouse.duckdb 是否被 DBeaver、另一个 Python/Streamlit 进程占用（关闭或结束进程后重试）；3）已安装 duckdb Python 包。刷新后红字错误会附带具体异常类型与原因。',
    footerHint:
      '说明：数据来自于当前 ODS 实例；修改映射或重新导入后，请刷新列表。失败文件请结合「文件上传」导入结果或历史批次记录核对。',
    linkUpload: '返回文件上传',
    linkHistory: '历史批次记录',
    deleteSessionBtn: '删除此导入会话',
    deleteBatchBtn: '删除整个批次',
    deleteSessionSessionsInBatch: '该批次在列表中共有 {n} 条导入会话。',
    deleteDialogSessionTitle: '删除当前导入会话',
    deleteDialogSessionBody:
      '将删除本会话在 ODS 中写入的 Parquet 文件、对应 manifest 以及 `ods_load_log` 中的本条记录。若同一文件路径仍被同批次的其它会话引用，则该文件会被保留。此操作不可恢复。',
    deleteDialogBatchTitle: '删除整个导入批次',
    deleteDialogBatchBody:
      '将删除该批次在 ODS 下的全部目录（`批次=…` 与 `manifests/批次=…`），并清除该批次在 `ods_load_log` 与 `ods_batch_state` 中的全部记录（所有导入会话）。此操作不可恢复。',
    deleteAckCheckbox: '我已知晓上述后果，确认删除',
    deleteConfirmInputLabel: '请输入批次 ID 以确认删除整个批次',
    deleteConfirmInputPlaceholder: '完整复制上方 KPI 中的批次 ID',
    deleteConfirmMismatch: '输入的批次 ID 与当前批次不一致',
    deleteCancel: '取消',
    deleteSubmit: '确认删除',
    deleteBusy: '删除中…',
    deleteErrorPrefix: '删除失败',
  },

  /** 历史批次记录（高保真界面原型：以 ODS 落盘日志聚合展示） */
  importHistoryUi: {
    pageTitle: '历史批次记录',
    pageBody:
      '按导入批次查看历史运行记录（当前阶段以 ODS 落盘日志为准）。可按批次/会话检索、查看会话概览，并从此处进入 ODS数据查看 或执行删除等运维操作。重跑入口先保留外观与交互壳，后续再接入方案 A 的实际重跑逻辑。',
    kpiSource: '数据来源（ODS 根目录）',
    listLoadErrorTitle: '批次列表加载失败',
    listLoadError: '无法加载批次列表',
    refresh: '刷新列表',
    refreshing: '刷新中…',
    ctaUpload: '前往文件上传',
    emptyCardTitle: '暂无历史批次',
    emptyBody: '当前环境尚无已导入批次。请先在「文件上传」完成导入后返回此页刷新。',
    listCardTitle: '批次列表',
    detailCardTitle: '批次详情',
    detailEmpty: '请选择左侧批次查看详情。',
    searchPlaceholder: '搜索批次 ID / 会话 ID…',
    typeFilterLabel: '类型',
    typeAll: '全部',
    totalHint: '共 {n} 条记录',
    colType: '类型',
    colBatch: '批次 ID',
    colSessions: '会话数',
    colSuccess: '成功/总文件',
    colFailed: '失败文件',
    colWarn: '告警',
    colLastTime: '最近导入',
    kpiBatchId: '批次 ID',
    kpiSessions: '会话数',
    kpiOdsFiles: 'ODS 文件数',
    kpiSuccess: '成功/总文件',
    kpiFailed: '失败文件',
    sessionSelectLabel: '选择会话',
    sessionKpiTitle: '选中会话',
    kpiLoadedAt: '导入时间',
    kpiFilesOk: '成功/总文件',
    kpiParquet: 'Parquet 路径数',
    gotoPreview: '新窗口预览',
    gotoPreviewHint: '在新窗口打开「ODS数据查看」，并自动选中当前批次/会话',
    rerunFailed: '重跑（仅失败）',
    rerunAll: '重跑（全量）',
    rerunSoonHint: '先展示界面与交互壳；后续接入方案 A 的实际重跑逻辑',
    typeExcelToOds: 'Excel→ODS',
    typeOdsToDwd: 'ODS→DWD',
    detailFootnote:
      '提示：当前页以 ODS 落盘日志聚合展示，后续可扩展到“格式检测快照 / 失败原因聚合 / ODS→DWD 状态”等。',
    deleteSessionBtn: '删除此会话产物',
    deleteBatchBtn: '删除整个批次',
    deleteDialogSessionTitle: '删除当前导入会话',
    deleteDialogSessionBody:
      '将删除本会话在 ODS 中写入的 Parquet 文件、对应 manifest 以及 `ods_load_log` 中的本条记录。若同一文件路径仍被同批次的其它会话引用，则该文件会被保留。此操作不可恢复。',
    deleteDialogBatchTitle: '删除整个导入批次',
    deleteDialogBatchBody:
      '将删除该批次在 ODS 下的全部目录（`批次=…` 与 `manifests/批次=…`），并清除该批次在 `ods_load_log` 与 `ods_batch_state` 中的全部记录（所有导入会话）。此操作不可恢复。',
    deleteAckCheckbox: '我已知晓上述后果，确认删除',
    deleteConfirmInputLabel: '请输入批次 ID 以确认删除整个批次',
    deleteConfirmInputPlaceholder: '完整复制上方批次 ID',
    deleteConfirmMismatch: '输入的批次 ID 与当前批次不一致',
    deleteNeedAck: '请勾选确认项',
    deleteCancel: '取消',
    deleteSubmit: '确认删除',
    deleteBusy: '删除中…',
    deleteError: '删除失败',
  },

  /** 加工中心：DWD 派生维/台账任务与运行记录 */
  processingDerivedTasksUi: {
    pageTitle: 'DWD 派生任务',
    pageDesc:
      '发票导入并完成 ODS→DWD 后，部分分析依赖的维度表不会自动与 DWD 完全同步，需要在此显式触发重算。下方列出当前已接入的任务、最近一次运行结果，以及历史台账（与「DWD→DIM」页中企业主数据等任务共用 ads_etl_task_run_log）。',
    taskRegistryTitle: '已接入的派生任务',
    taskNameCol: '任务',
    taskCodeCol: '任务码',
    dependsCol: '依赖',
    outputCol: '产出表',
    triggerHintCol: '触发方式',
    enterpriseYearRelName: '企业年度购销标志重算',
    enterpriseYearRelCode: 'dim.enterprise_year_rel.rebuild',
    enterpriseYearRelDepends: 'dwd_inv_header、dim_group_enterprise_year、dim_subject_master（org）',
    enterpriseYearRelOutput: 'dim_enterprise_year_rel',
    enterpriseYearRelTriggers: '本页手动；ODS→DWD 请求体 rebuild_enterprise_year_rel；API POST /api/dim/enterprise-year-rel/rebuild',
    enterpriseYearRelWhy:
      '仅「当年集团台账成员」且能映射到 org 主体的企业写入本表：按各 stat_year 将 DWD 销方/购方与成员税号对齐，写入购销双向标志；无票年仍保留一行（标志为假）。未指定年度时重算 **DWD 发票年度 ∪ 台账年度** 并集，以便多年发票与多年台账逐年度对齐。',
    metaCardTitle: '数据与年度概览',
    metaDwdYears: 'DWD 中出现的发票统计年度',
    metaGroupYears: '集团台账（dim_group_enterprise_year）统计年度',
    metaUnionYears: '重算默认并集（DWD ∪ 台账，去重）',
    metaDimCounts: '当前 dim_enterprise_year_rel 按年行数',
    metaEmpty: '（无）',
    yearPickTitle: '选择要重算的年份',
    yearPickHint:
      '勾选下方年度后「重算选中年度」；不勾选则「重算全部年度」按 **DWD 发票年度 ∪ 集团台账年度** 推断。并集含发票中其他统计年度，便于逐年对比报送标志。',
    selectAllDwdYears: '全选并集年度',
    clearYears: '清空选择',
    rebuildSelected: '重算选中年度',
    rebuildAll: '重算全部年度（DWD）',
    dryRunBtn: '预演（不写库）',
    dryRunHint: '预演仅统计将写入行数，不产生运行台账终态（不写 dim 表）。',
    busyMeta: '加载概览中…',
    busyRebuild: '重算执行中…',
    busyRuns: '加载运行记录中…',
    lastResultTitle: '本次执行结果',
    runsTitle: '运行记录（本任务）',
    runsAllTitle: '近期全部维度任务',
    runsAllHint: '含 DWD→DIM 企业主数据/映射等其它任务，便于对照导入后整条链路。',
    colTime: '开始时间',
    colStatus: '状态',
    colDuration: '耗时',
    colTrigger: '来源',
    colRows: '影响行数',
    colError: '错误信息',
    colTask: '任务码',
    refreshRuns: '刷新记录',
    errPrefix: '操作失败：',
    linkOdsToDwd: '前往 ODS→DWD',
  },

  /** ODS→DWD 处理中心（高保真界面原型：任务中心/控制台视角） */
  odsToDwdCenterUi: {
    pageTitle: 'ODS→DWD',
    pageBody:
      '按批次把已落盘到 ODS 的数据构建到 DWD（清洗、标准化、去重、质量校验）。默认执行「增量构建」：只处理还没写入 DWD 水位的导入会话；「强制重洗」仅用于已有 DWD 水位的会话（先删旧行再重算）。若会话还没有 DWD 水位，请用批量或单次增量构建。详见 `docs/ODS到DWD增量构建与强制重洗.md`。',
    refresh: '刷新列表',
    refreshing: '刷新中…',
    emptyCardTitle: '暂无可处理批次',
    emptyBody: '当前环境尚无已导入批次可用于 DWD 构建。请先在「文件上传」完成导入。',
    /** 有批次数据但当前状态/搜索无匹配时展示；须保留状态切换入口 */
    filterNoMatchBatches:
      '当前筛选下没有匹配的批次。请调整状态下拉框或清空搜索；例如选「全部状态」或「已构建」可查看已写入 DWD 的批次。',
    filtersCardTitle: '筛选与批次范围',
    searchPlaceholder: '搜索批次 ID…',
    statusAll: '全部状态',
    statusNotBuilt: '未构建',
    statusRunning: '构建中',
    statusSucceeded: '已构建',
    statusFailed: '失败',
    listCardTitle: '批次队列',
    detailCardTitle: '批次详情',
    colBulkExpand: '批量',
    bulkToolbarHint: '勾选批次表示选中该批次下全部导入会话；展开后可只选部分会话。与右侧单次「开始构建」独立。',
    rebuildEnterpriseYearRelLabel: '构建成功后重算企业年度购销标志（dim_enterprise_year_rel）',
    rebuildEnterpriseYearRelHint:
      '勾选后，在本次 DWD 增量构建成功时，按 **本次构建涉及年度 ∪ 集团台账中出现的年度** 重算 dim_enterprise_year_rel：仅「当年 dim_group_enterprise_year 成员」且能映射到 org 主体的企业写入购销双向标志（与「发票报送覆盖分析」分母一致）；并集会带上其他台账年度以免漏刷。失败时可到「加工中心 → DWD派生任务」手动重算或查看运行台账。',
    bulkSelectAllFiltered: '全选（当前筛选）',
    bulkClearSelection: '清空选择',
    bulkIncrementalBuild: '批量增量构建',
    bulkIncrementalSummary: '{b} 个批次 · {s} 个会话',
    bulkIncrementalFailPrefix: '批量增量失败：',
    bulkExpandSessions: '展开会话',
    bulkCollapseSessions: '收起',
    colBatch: '批次',
    colOds: 'ODS',
    colDwd: 'DWD',
    colQuality: '质量闸门',
    colUpdated: '更新时间',
    badgeNotBuilt: '未构建',
    badgeRunning: '构建中',
    badgeSucceeded: '已构建',
    badgeFailed: '失败',
    kpiBatchId: '批次 ID',
    kpiOdsFiles: 'ODS 文件数',
    kpiEstRows: 'ODS 导入行数（日志）',
    kpiDwdRows: 'DWD 行数',
    kpiLastRun: '最后构建',
    kpiDuration: '耗时',
    actionsTitle: '操作',
    actionBuild: '开始构建（增量）',
    /** 左侧展开列表标题 */
    bulkExpandedSessionListTitle: '各导入会话（勾选参与批量增量；仅已有 DWD 水位的会话显示「强制重洗」）',
    /** 右侧详情区 */
    detailForceRebuildHint:
      '「强制重洗」仅适用于已完成过增量 DWD（已有水位）的会话；尚未落盘 DWD 的会话请用「批量增量构建」或右侧「开始构建（增量）」。',
    /** 无水位时会话行不展示强制重洗按钮时的说明 */
    forceRebuildUnavailableHint: '该会话尚无 DWD 水位，请先执行增量构建；强制重洗用于覆盖已落盘数据。',
    sessionWatermarkHint: 'DWD 水位',
    forceRebuild: '强制重洗',
    forceRebuildHint: '删除该会话在 DWD 中曾写入的行并重算（需确认）',
    forceRebuildConfirm:
      '将删除该导入会话在已接入 DWD 表中的行，并重置 ods_load_log 水位后重跑清洗。此操作不可自动撤销，是否继续？',
    actionRetryFailed: '重跑失败步骤',
    actionRollback: '回滚该批次',
    actionViewLogs: '查看日志',
    actionBuildHint: 'POST /api/dwd/build（默认 incremental=true）；请保持 Local API 已启动',
    /** Vite 代理连不上 8765 或上游无响应时常见 502 */
    httpErrorProxy502:
      '无法连接本地 API（HTTP {status}）。请确认已运行 dev.bat，且标题为「InvoiceLens-LocalAPI」的窗口未关闭，127.0.0.1:8765 正在监听；若仍失败，可在 frontend/.env 设置 VITE_LOCAL_API_BASE=http://127.0.0.1:8765 绕过代理直连。',
    actionBuildTitle: '仅处理尚未记录 DWD 水位的会话，将 ODS 写入已接入 DWD 表',
    actionDisabledHint: '下列能力尚未接入：重跑单步 / 回滚 / 日志文件视图',
    stepperTitle: '流水线步骤',
    steps: {
      readOds: '读取 ODS',
      standardize: '清洗/标准化',
      dedupe: '主键去重',
      enrich: '维度关联',
      writeDwd: '写入 DWD',
      validate: '质量校验',
    },
    panelsTitle: '观测与指标',
    tabLogs: '构建日志',
    tabMetrics: '指标概览',
    logsPlaceholder: '此处展示流水线日志（后续对接后端事件流/日志文件）。',
    logsPrototypeNote:
      '尚未在本页执行「开始构建」时无日志。点击「开始构建（增量）」或「强制重洗」后，此处将显示本次 API 返回的摘要。若列表 DWD 仍为「未构建」，请先完成 Excel→ODS 导入并确保 Local API 可访问 DuckDB。',
    metricsPlaceholder:
      '此处展示质量闸门指标（空值率、重复率、金额校验等）。先做高保真布局，待规则确认后接入计算与落库。',
    metricsPrototypeNote: '说明：下列百分比与数字为布局占位，非真实质检结果。',
    /** 与 run_cleaner 返回的 dq_* 键一致，用于构建日志摘要 */
    dqReportSectionTitle: '专项与 inv_detail 数据质量（本批）',
    dqReportAllOk: '专项与 inv_detail：行数/金额对账未见异常项。',
    dqReportLabels: {
      dq_spc_transport_passenger_linecount_mismatch: '客运专项：正行行数≠明细',
      dq_spc_transport_freight_linecount_mismatch: '货运专项：正行行数≠明细',
      dq_spc_vehicle_sales_linecount_mismatch: '机动车专项：正行行数≠明细',
      dq_spc_construction_linecount_mismatch: '建筑服务专项：正行行数≠明细',
      dq_spc_estate_lease_linecount_mismatch: '不动产租赁专项：正行行数≠明细',
      dq_spc_transport_passenger_amount_vs_inv_detail: '客运专项：金额或明细 UUID 对账',
      dq_spc_transport_freight_amount_vs_inv_detail: '货运专项：金额或明细 UUID 对账',
      dq_spc_vehicle_sales_amount_vs_inv_detail: '机动车专项：金额或明细 UUID 对账',
      dq_spc_construction_service_amount_vs_inv_detail: '建筑服务专项：金额或明细 UUID 对账',
      dq_spc_estate_lease_amount_vs_inv_detail: '不动产租赁专项：金额或明细 UUID 对账',
    },
  },

  dwdToDimCenterUi: {
    prototypeBadge: '界面原型',
    pageTitle: 'DWD→DIM 任务中心',
    pageBody:
      '统一管理 DWD→DIM 多任务构建（注册表带编号与说明、触发、重跑与日志）。任务状态与运行记录来自 ads_etl_task_run_log 台账，运行中任务每 1.5 秒自动刷新。',
    tasksLoading: '同步中…',
    refresh: '刷新',
    kpiTaskCount: '已注册任务',
    kpiRunningCount: '运行中任务',
    kpiQueueDepth: '排队深度',
    kpiQueuedTaskCount: '排队任务',
    activeRunsTitle: '正在执行',
    activeRunsHint: '来自统一台账与后台队列的实时运行；点击可定位到任务详情。',
    activeRunsEmpty: '当前无运行中任务。',
    queueSlotsTitle: '队列与并发槽位',
    queueSlotsHint: '用于展示多任务排队执行策略；当前为原型占位。',
    queueSlotIdle: '空闲',
    queueSlotBusy: '执行中',
    queuePriorityLabel: '优先级',
    queueWaitingLabel: '等待队列',
    dagTitle: '任务依赖关系（DAG）',
    dagHint: '展示任务编排依赖，仅用于评审与运维确认，不代表实时执行图。',
    dagNodeDependsOn: '依赖',
    dagNodeOutput: '输出',
    dagNodeClickHint: '点击节点在右侧查看详情',
    dagEdgeHighlightNote: '高亮：与当前选中任务相关的依赖边',
    dagEdgeClickHint: '点击某条边可选中该边的下游任务（箭头右侧）',
    failureRowClickHint: '点击整行定位到右侧运行日志',
    logFailureTitle: '失败上下文（关联选中）',
    logFailureLine1: '错误类型：{errorType}',
    logFailureLine2: '失败时间：{lastFailAt}',
    logFailureLine3: '下一步：按建议动作重试或打开运行详情核对依赖与数据。',
    taskListTitle: '任务清单',
    taskListHint: '按注册表序号展示；点击行查看作用、产出与查询说明。',
    colTaskNo: '编号',
    queueHint: '当前排队 {count} 个待执行项',
    querySourceFilter: '数据来源',
    querySourceAll: '全部来源',
    colQuerySource: '查询来源',
    colTaskName: '任务',
    colOutput: '输出表',
    colTriggerMode: '触发模式',
    colQueue: '队列',
    colStatus: '状态',
    statusIdle: '空闲',
    statusQueued: '排队中',
    statusRunning: '执行中',
    statusFailed: '失败',
    triggerManual: '手动',
    triggerChained: '串联',
    triggerScheduled: '定时',
    taskDetailTitle: '任务详情',
    emptyTaskDetail: '请选择左侧任务查看参数、依赖与运行记录。',
    detailDomain: '业务域',
    detailOwner: '负责人',
    detailOutput: '产出',
    detailDependsOn: '注册依赖',
    detailSoftDependsOn: '建议先决',
    detailLayer: '产出层级',
    detailPurpose: '作用',
    detailOutputDesc: '产出数据',
    detailQueryDesc: '主要查询',
    detailLastRun: '最近运行',
    detailDuration: '耗时',
    detailProgress: '当前步骤',
    runLogTitle: '最近运行摘要',
    runLogColStatus: '状态',
    runLogColStartedAt: '开始时间',
    runLogColDuration: '耗时',
    runLogColRows: '影响行数',
    runLogColError: '错误摘要',
    runLogColTask: '任务',
    runLogUnknownTask: '（未注册任务）',
    runLogDialogTitle: '全部运行记录',
    runLogFilterTask: '任务筛选',
    runLogFilterTaskAll: '全部任务',
    runLogFilterStatus: '状态筛选',
    runLogFilterStatusAll: '全部状态',
    runLogStatusSuccess: '成功',
    runLogStatusFailed: '失败',
    runLogStatusRunning: '执行中',
    runLogPagePrev: '上一页',
    runLogPageNext: '下一页',
    runLogPageInfo: '第 {page} / {total} 页',
    runLogLoading: '加载运行记录中…',
    runLogEmpty: '暂无运行记录。',
    runStatusSuccess: '成功',
    runStatusFailed: '失败',
    runStatusRunning: '执行中',
    logSample1: 'run_id: DIM-20260426-130201 · trigger_source: manual',
    logSample2: 'step: read_dwd_header -> aggregate_enterprise -> upsert_dim',
    logSample3: 'rows_affected: 12,438 · calc_version: v1-alpha',
    viewRuns: '查看全部运行记录',
    triggerNow: '立即触发',
    runDialogTitle: '触发任务',
    runDialogBody: '确认后将任务写入统一队列，由调度器按优先级串行/并行执行。',
    runModeLabel: '构建模式',
    runModeIncremental: '增量构建（推荐）',
    runModeFull: '全量重算（运维）',
    dependStrategyLabel: '依赖策略',
    dependStrategyAuto: '自动检查依赖并等待',
    dependStrategyIgnore: '忽略依赖（仅调试）',
    runQueueNote: '提示：多任务排队时，系统将基于任务依赖和资源配额自动调度执行顺序。',
    failurePanelTitle: '失败态与重试建议',
    failurePanelHint: '聚合最近失败任务，便于快速定位与批量重试策略评估。',
    failurePanelEmpty: '近期无失败任务。',
    failureColTask: '任务',
    failureColErrorType: '错误类型',
    failureColLastFail: '最近失败',
    failureColAction: '建议动作',
    failureActionRetry: '重试一次',
    failureActionInspect: '查看运行详情',
    cancel: '取消',
    confirmRun: '确认加入队列',
    runNotImplementedHint: '该任务尚未接入真实执行。',
    runSubmitBusy: '提交中…',
    runSubmitRunning: '执行中…',
    runDialogProgressTitle: '当前进度',
    runDialogProgressRunId: '运行 ID：{runId}',
    runDialogProgressStep: '步骤：{step}',
    runDialogProgressElapsed: '已用时：{elapsed}',
    runDialogProgressHint: '任务在后台执行，本窗口将实时刷新步骤说明；请勿关闭浏览器标签页。',
    groupEnterpriseRebuildSuccess: '集团成员表已更新（run {runId}，写入 {rows} 行）{extra}',
    groupEnterpriseTaskHint:
      '数据来源：「维度管理 → 被审企业组织 → 管理与产权层级信息」中的 dim_audited_enterprise_registry；计算产出 dim_group_enterprise_year，供一级企业名单与报送覆盖分析引用。',
    runSubmitAsyncStarted: '任务已在后台启动（run {runId}），正在等待完成…',
    runSubmitSuccess: '任务已触发：{runId}（写入 {rows} 行，企业 {ents} 个）。',
    runSubmitSuccessRows: '任务已触发：{runId}（影响 {rows} 行）。',
    runSubmitFailed: '任务触发失败：{message}',
    runSubmitScopeSuffix: '（主体类别范围：{scope}）',
    subjectTaskIngestName: '主体库 · 从 DWD 归集',
    subjectTaskRecomputeName: '主体库 · 重算（分类+关联）',
    subjectTaskRenameName: '主体库 · 重建更名信号',
    subjectTaskDomain: '主体库',
    overwriteManualRepairsLabel: '覆盖人工修正的类别字段（慎用）',
    overwriteManualRepairsHint:
      '默认保留「数据修正」写过的 subject_category / org_category；勾选后本任务可覆盖这些字段。',
    recomputeWithRelationsLabel: '同时重建主体关联（TRADE_COUNTERPARTY）',
    subjectIngestSuccess: '归集完成：{count} 个主体（run {runId}）{extra}',
    subjectRecomputeSuccess: '分类重算完成（run {runId}）{extra}',
    subjectRenameSuccess: '更名信号重建完成{extra}',
    subjectPipelineTaskName: '主体库 · 一键全流程（归集→重算→更名）',
    subjectPipelineSuccess:
      '全流程完成：归集 {ingestCount} 个主体；分类 run {recomputeRunId}；更名{renameExtra}',
    subjectPipelineStepIngest: '正在从 DWD 归集主体…',
    subjectPipelineStepRecompute: '正在重算分类与关联…',
    subjectPipelineStepRename: '正在重建更名信号…',
    subjectPipelineStarted: '全流程已在后台启动（run {runId}）…',
    subjectPipelineFinished: '主体库全流程已完成{extra}',
    subjectTaskRunLogHint: '主体库任务运行记录可在下方「最近运行摘要」与「查看全部运行记录」中查看（写入 ads_etl_task_run_log）。',
  },

  /** 加工中心：DWD数据查看（对齐 ODS数据查看 的批次/会话筛选与运维删除） */
  dwdPreviewUi: {
    pageTitle: 'DWD数据查看',
    pageBody:
      '查看已通过「ODS→DWD」写入 DuckDB 的数据。Tab 以 DWD 物理表为主（来自 dwd_mapping），仅展示当前批次/会话在 DWD 有数据的表。删除操作仅移除 DWD 落库行并清空对应 DWD 水位，不删除 ODS Parquet。',
    refresh: '刷新列表',
    refreshing: '加载中…',
    emptyListTitle: '暂无导入批次',
    emptyListBody: '请先在「文件上传」完成导入，并在「ODS→DWD」中构建 DWD。',
    batchCardTitle: '选择批次 / 导入会话',
    filterCardTitle: '快速切换 DWD 表',
    tabsLoading: '正在同步 DWD 表…',
    noTabsHint:
      '当前批次/范围下没有可展示的 DWD Tab（可能尚未构建、或该表未接入 DWD 预览映射）。可先刷新列表或到「ODS→DWD」构建。',
    labelBatch: '导入批次',
    labelSession: '导入会话',
    sessionAll: '整批（全部会话）',
    layerHeader: '主表（header 口径）',
    layerDetail: '明细（detail 口径）',
    loadFirstPage: '加载数据',
    loadMore: '加载更多',
    loadAll: '全部加载',
    loadAllHint:
      '按接口单次最多 500 行连续拉取，直至无更多或达到上限（{max} 行）；便于在浏览器内全文/按列筛选。超大数据集请改用导出或专用查询。',
    loadAllCapped: '已达到单次「全部加载」上限 {max} 行，已暂停。可继续点击「加载更多」分段拉取。',
    alreadyFullyLoaded: '当前 Tab 下数据已全部在浏览器中。',
    loading: '读取中…',
    totalRows: '本筛选约 {n} 行',
    totalUnknown: '行数统计不可用',
    noRows: '当前筛选下无 DWD 行（可能尚未构建或会话不匹配）。',
    tableHint: '列较多时可横向滚动；值为空表示 NULL。',
    searchLabelFulltext: '全文',
    searchPlaceholder: '在已加载数据中搜索（匹配任意列）…',
    columnFilterTitle: '按列筛选',
    /** 单行工具条内与「全文」并列时的短标签 */
    columnFilterInline: '按列',
    columnPick: '列',
    columnContains: '包含',
    addColumnFilter: '添加条件',
    clearFilters: '清除筛选',
    filterChipRemove: '移除此条件',
    filteredCount:
      '已加载 {loaded} 行 · 筛选后 {shown} 行',
    filterNoMatch: '当前条件下无匹配行，可调整关键字/列条件，或先「加载更多」扩大已加载范围。',
    searchScopeNote:
      '说明：筛选仅在当前已加载到浏览器的行内生效；未分页加载的数据不会参与匹配。',
    apiHint: 'GET /api/dwd-preview/tabs · GET /api/dwd-preview/table-page · POST /api/dwd-preview/delete',
    kpiBatchId: '批次 ID',
    kpiSession: '会话',
    kpiDwdHeader: 'DWD 主表行（本会话/合计）',
    kpiDwdDetail: 'DWD 明细行（本会话/合计）',
    kpiDwdWatermark: 'DWD 水位',
    watermarkNone: '未构建',
    deleteSessionBtn: '删除本会话 DWD 落库',
    deleteBatchBtn: '删除本批次 DWD 落库',
    deleteSessionSessionsInBatch: '该批次在列表中共有 {n} 条导入会话。',
    deleteSessionNeedPick:
      '请先在下拉框中选择**某一导入会话**（勿选「整批」）后再删除本会话 DWD 落库。',
    deleteDialogSessionTitle: '删除当前导入会话的 DWD 落库',
    deleteDialogSessionBody:
      '将删除该会话在已接入 DWD 表中 `import_batch_id`+`import_session_id` 匹配的全部行，并把 `ods_load_log.dwd_session_processed_at` 置空。**不会**删除 ODS Parquet。删除后可至「ODS→DWD」重新增量构建。',
    deleteDialogBatchTitle: '删除整个导入批次的 DWD 落库',
    deleteDialogBatchBody:
      '将删除该**批次 ID** 下全部会话写入的 DWD 行，并把该批次所有会话的 DWD 水位置空。**不会**删除 ODS 目录与 Parquet。删除后可至「ODS→DWD」重新增量构建。',
    deleteConfirmInputLabel: '请输入批次 ID 以确认删除整批 DWD',
    deleteConfirmInputPlaceholder: '完整复制上方 KPI 中的批次 ID',
    deleteConfirmMismatch: '输入的批次 ID 与当前批次不一致',
    deleteAckCheckbox: '我已知晓上述后果，确认删除 DWD 落库数据',
    deleteNeedAck: '请勾选确认项',
    deleteCancel: '取消',
    deleteSubmit: '确认删除',
    deleteBusy: '删除中…',
    deleteErrorPrefix: '删除失败',
    footerHint:
      '说明：与「ODS数据查看」中删除 ODS 不同，此处仅清理 DuckDB 中 DWD 层数据；ODS 文件仍保留，需重新构建时请使用加工中心「ODS→DWD」。',
    linkOdsToDwd: '前往 ODS→DWD',
    linkOdsPreview: '前往 ODS数据查看',
  },

  /**
   * 数据质量报告：高保真界面原型（占位数据，不接后端）
   */
  dataQualityPrototype: {
    prototypeBadge: '界面原型',
    prototypeNote: '本页数字、图表与表格均为高保真占位，用于评审信息架构与交互；接入 DuckDB / cleaner 的 dq_* 结果后替换数据源即可。',
    overviewTitle: '数据质量 · 按域总览',
    overviewLead:
      '按「质量域」组织结论：先唯一性与重复，再跨表对齐（logic_line_no），再头明对账，其次语义与血缘。各域内可下钻到异常明细。',
    batchLabel: '当前批次（演示）',
    batchOpt1: 'batch_demo_2026Q1 · 进项合并',
    batchOpt2: 'batch_demo_2025YE · 销项抽样',
    kpiScanned: '已扫描发票（票）',
    kpiAnomaly: '存在异常的票',
    kpiBlock: '阻塞级',
    kpiWarn: '警告级',
    kpiInfo: '提示级',
    domainSection: '质量域',
    domainA_title: '身份与键 · 唯一性',
    domainA_body: '票键在本批次内是否唯一；是否存在应合并的重复头记录。',
    domainA_metric1: '重复票头组',
    domainA_metric2: '涉及票数',
    /** 购销方纳税人识别号 / 统一社会信用代码（原型占位） */
    domainTaxId_title: '购销方识别号 · 空值与长度',
    domainTaxId_body:
      '主表「购方识别号」「销方识别号」：任一为空计为一条票级异常；「非18位」指去空白后长度不为 18（不含已计入空值的字段，避免重复计数）。正式接入时可对境外主体、旧 15 位税号等加白名单。',
    domainTaxId_metric1: '购方或销方识别号为空（票）',
    domainTaxId_metric2: '购方或销方识别号非18位（票）',
    domainTaxId_breakdown: '演示拆分：仅购方空 74 · 仅销方空 31 · 双空 22',
    domainB_title: '跨表对齐',
    domainB_body:
      '信息汇总与客运/货运/建筑等专项在「同票 + logic_line_no」下是否行位一致；与 dwd_inv_detail 行数 / detail_uuid 对账。',
    domainB_metric1: '行数不一致票',
    domainB_metric2: 'UUID 对账异常',
    domainC_title: '头明对账',
    domainC_body: '发票主表价税合计、不含税、税额与明细汇总（及容差规则）是否一致。',
    domainC_metric1: '不平账票',
    domainC_metric2: '最大差额（演示）',
    domainD_title: '语义与专项覆盖',
    domainD_body: '票面特征与专项 sheet 是否匹配；「详见销货明细」等汇总行识别是否异常。',
    domainD_metric1: '疑似缺专项',
    domainD_metric2: '汇总行规则命中',
    domainE_title: '血缘与可追溯',
    domainE_body: '源 Excel、sheet、ODS 序号与拒收行样本；便于复核与导出。',
    domainE_metric1: '行级拒收（本批）',
    domainE_metric2: '文件级阻断',
    severityBlock: '阻塞',
    severityWarn: '警告',
    severityInfo: '提示',
    viewRules: '查看域内规则',
    goDetail: '打开异常明细',
    goTrend: '查看质量趋势',
    dupSectionTitle: '重复记录 · 各对象判定标准',
    dupSectionLead:
      '主表、明细、各专项的「重复」定义不同；列表页与下钻页将固定展示本列，避免与「头明对账」「logic_line_no 对齐」混淆。',
    dupColObject: '对象',
    dupColRule: '判定标准（产品口径）',
    dupColCount: '本批疑似组数',
    dupHdr: '发票主表',
    dupHdrRule: '同一导入范围内，归一化票键（代码+号码+数电号码等）出现 ≥2 条头记录。',
    dupDtl: '发票明细',
    dupDtlRule: '同票下 detail_uuid（或票键+logic_line_no）在应唯一集合中重复；或同源文件+sheet+序号完全重复落盘。',
    dupSpc: '专项（客运/货运/建筑/机动车/不动产租赁等）',
    dupSpcRule: '按各专项配置的「业务重复键」分组（字段组合因专项而异，如建筑：发生地+项目摘要片段+金额+日期等）。',
    rulesSectionTitle: '规则清单（折叠占位）',
    rulesExpand: '展开示例',
    rulesCollapse: '收起',
    ruleR1: '专项正行行数 vs 信息汇总明细（logic_line_no>0）',
    ruleR2: '专项金额 / detail_uuid 与 inv_detail 对账',
    ruleR3: '头表价税合计 vs 明细价税汇总',
    ruleR4: '主表票键重复组',
    ruleR5: '明细逻辑行重复（detail_uuid）',
    ruleR6: '购方或销方识别号为空；有值但长度≠18（统一社会信用代码常规长度）',
    sampleSectionTitle: '异常抽样（演示）',
    sampleColTicket: '票键（脱敏）',
    sampleColDomain: '质量域',
    sampleColRule: '规则',
    sampleColSev: '严重度',
    sampleColDelta: '摘要',
    sampleRowTaxIdRule: '购销方识别号 · 空值/长度',
    sampleRowTaxIdDelta: '销方识别号空；购方 913301… 为 17 位',
    detailTitle: '数据质量 · 异常明细',
    detailLead: '按域、严重度、专项类型筛选；列表示例与导出占位。',
    filterCardTitle: '筛选条件',
    filterDomain: '质量域',
    filterSeverity: '严重度',
    filterSpec: '专项类型',
    filterAll: '全部',
    colDetectedAt: '检出时间',
    colActions: '操作',
    exportCsvDisabled: '导出 CSV（占位）',
    actionDrill: '带入并验证',
    linkBackOverview: '返回质量概览',
    trendTitle: '数据质量 · 趋势',
    trendLead: '按周聚合异常票数与阻塞数（演示）；后续按 stat_year / import_batch 接入。',
    trendWeek: '周次',
    trendAnomaly: '异常票',
    trendBlock: '阻塞',
    trendNote: '柱状图为 CSS 占位，非图表库。',
  },

  healthScoreUi: {
    prototypeBadge: '界面原型',
    pageTitle: '被审企业健康度评价',
    pageDesc:
      '面向被审企业（审计关联企业库、管理树或产权树企业）基于发票数据输出健康分，并按“阈值命中 -> 可能疑点方向 -> 建议核查动作”提供可解释说明，便于直接下钻审计疑点。',
    kpiTotalScore: '健康总分',
    kpiGrade: '等级',
    kpiChange: '较上期变化',
    kpiRule: '等级规则',
    dimensionTitle: '维度得分（含权重）',
    topDeductionTitle: '扣分Top3（按权重影响）',
    indicatorTableTitle: '指标明细与疑点方向',
    tableLead: '每行展示计算公式、阈值判定与疑点方向；点击“查看计算依据”可展开完整说明。',
    levelAll: '全部预警类型',
    levelNormal: '仅正常',
    levelWarning: '仅预警',
    levelAlert: '仅异常',
    dimensionAll: '全部指标类型',
    onlyAbnormal: '仅看预警/异常指标',
    resetFilters: '重置筛选',
    colIndicator: '指标',
    colValue: '当前值',
    colScore: '得分',
    colThreshold: '阈值分档',
    colJudgement: '阈值判定',
    colSuspicion: '可能疑点方向',
    colAction: '操作',
    viewLogic: '查看计算依据',
    loadingText: '加载中…',
    loadFailedPrefix: '健康度数据加载失败：',
    drawerTitle: '指标计算依据',
    close: '关闭',
    formulaLabel: '计算公式',
    thresholdLabel: '阈值分档',
    sourceLabel: '数据来源',
    hitBandLabel: '命中区间',
    evidenceLabel: '样本证据数',
    explainLabel: '判定说明',
    suspicionBlockTitle: '可能疑点方向',
    actionBlockTitle: '建议核查动作',
    selectHint: '点击左侧表格中的“查看计算依据”后，在此查看详情。',
    emptyHint: '暂无可展示内容',
  },

  subjectCategoryUi: {
    pageTitle: '主体类别',
    pageDesc:
      '基于 GB 32100-2015 与登记口径预置主体分类；维护匹配规则说明与默认风险关注，供主体库与后续分析引用。编辑确认后即写入 config/subject_category_rules.yaml。',
    kpiPresetCount: '预置类别数',
    kpiEnabledCount: '启用类别数',
    kpiCoverageCount: '覆盖主体数',
    kpiVersion: '标准版本',
    standardVersion: 'GB32100-2015',
    tableTitle: '类别清单与启用状态',
    filterKeyword: '关键词检索',
    filterKeywordPlaceholder: '类别编码 / 名称 / 登记部门 / 法律形态 / 匹配规则 / 风险关注',
    filterStatus: '启用状态',
    filterStatusAll: '全部',
    filterStatusEnabled: '仅启用',
    filterStatusDisabled: '仅停用',
    filterReset: '重置',
    colCategoryCode: '类别编码',
    colCategoryName: '类别名称',
    colGbCode: '标准编码',
    colRegisterAuthority: '登记部门',
    colLegalForm: '法律形态',
    colInvoiceScene: '匹配规则说明',
    colDefaultRiskFocus: '默认风险关注',
    riskFocusExpand: '展开',
    riskFocusCollapse: '收起',
    colCoverage: '覆盖主体',
    colAction: '操作',
    colStatus: '状态',
    statusEnabled: '启用',
    statusDisabled: '停用',
    addCategoryBtn: '新增类别',
    editBtn: '编辑',
    addDialogTitle: '新增主体类别',
    editDialogTitle: '编辑主体类别',
    formCode: '类别编码',
    formName: '类别名称',
    formGbCode: '标准编码',
    formRegisterAuthority: '登记部门',
    formLegalForm: '法律形态',
    formScene: '匹配规则说明',
    formRiskFocus: '默认风险关注',
    formEnabled: '启用该类别',
    formNeedCodeName: '请至少填写类别编码与类别名称。',
    formCodeDuplicated: '类别编码重复，请更换后重试。',
    dialogCancel: '取消',
    dialogConfirm: '确认',
    bannerSavedLocal: '页面内已更新并自动保存到配置文件。',
    bannerSavedLocalDraft: '本地 API 当前不可达，已先保存到浏览器草稿；待 API 恢复后可重新编辑并自动保存。',
    bannerSavedDraftAfterFail: '保存到 YAML 失败，已先保存到浏览器草稿；修复错误后可再次保存。',
    bannerSavedYaml: '主体类别规则已自动保存到 YAML。',
    bannerSaveFailed: '保存失败，请检查本地 API 与规则格式。',
    bannerOfflineMode: '本地 API 不可达，当前以页面内预置/本地草稿继续编辑；不影响新增与修改。',
    detailTitle: '类别详情',
    emptyHint: '当前筛选下没有可展示的主体类别。',
    detailGbCode: '标准编码',
    detailLegalForm: '法律形态',
    detailInvoiceScene: '匹配规则说明',
    detailRiskFocus: '默认风险关注',
    detailCoverage: '覆盖主体数',
    rebuildTitle: '历史重算 / 回填',
    rebuildDesc:
      '若你修改了主体类别规则并希望历史入库数据同步生效，需要执行一次 DWD→DIM 重算/回填任务。页面中的“启用/停用”不会自动改写历史记录。',
    rebuildCta: '去 DWD→DIM 发起重算',
    rebuildHint: '建议按批次或统计年度分段执行，先小范围验证后全量推广。',
    rebuildFallbackHint: '当前环境无法自动跳转。请前往“加工中心 → DWD→DIM”，选择目标批次后执行重算/回填任务。',
    recomputeRunNow: '立即重算（分类+关联）',
    recomputeRunning: '重算中…',
    recomputeMovedHint: '分类重算已迁至「加工中心 → DWD→DIM → 主体库 · 重算（分类+关联）」；下方仅展示最近一次运行摘要。',
    recomputeLatestTitle: '最近一次重算摘要',
    recomputeLatestEmpty: '暂无重算记录，可点击“立即重算（分类+关联）”生成首条快照。',
    recomputeLatestRunId: '运行批次',
    recomputeLatestSnapshotId: '快照批次',
    recomputeLatestCreatedAt: '执行时间',
    recomputeLatestCategory: '分类：总数 {total}，命中 {matched}，需复核 {needsReview}，停用拦截 {disabledBlocked}',
    recomputeLatestRelation: '关联：关系 {relationTotal} 条，交易发票 {invoiceCount} 张，交易金额 {amount}',
    recomputeLatestDistTitle: '分类分布（按 org_category）',
    recomputeLatestDistColCategory: '类别编码',
    recomputeLatestDistColCategoryName: '类别名称',
    recomputeLatestDistColCount: '数量',
    recomputeLatestDistColRatio: '占比',
    recomputeLatestTop1Badge: 'TOP1',
    recomputeLatestTop3Ratio: 'Top3 累计占比：{ratio}',
    recomputeLatestTop1HighConcentration: 'Top1 占比偏高（>{threshold}%），请关注主体类别集中度与规则覆盖面。',
  },

  dimVersionUi: {
    prototypeBadge: '界面原型',
    pageTitle: '维度 · 年度口径版本',
    pageDesc:
      '本页只管理「维度层」在某一统计年度下的默认生效快照：全量企业库、票企映射、被审企业树等分析页，默认按哪一批数据、哪一版规则来汇总。不在这里改单张发票或单笔导入记录。',
    pageNote:
      '操作边界：发布 = 将该版本设为当年「对外口径」；回滚 = 切回历史已发布版本为当前生效。每个年度同时只能有一个「当前生效」的已发布版本。后续会对接真实版本表与审计日志。',
    scopeCardTitle: '管理对象（读一遍就懂）',
    scopeCardLead: '版本号背后绑定的是一整份「年度维度聚合结果」的快照边界，典型包括：',
    scopeBullet1: '主体库：该年度主体清单从哪一批算到哪一批、是否并入外部导入。',
    scopeBullet2: '发票报送覆盖分析等：覆盖与成员口径类 KPI 随生效版本切换（与上面主体快照一致）。',
    scopeBullet3: '被审企业组织树：关系与节点统计使用的规则版本号、批次范围与上两项对齐。',
    moreTipsToggle: '查看更多操作提示',
    lessTipsToggle: '收起操作提示',
    createDraftBtn: '基于当前生效版新建草稿',
    headerCardTitle: '当前年度的维度生效口径',
    filterYearLabel: '统计年度',
    kpiCurrentVersion: '当前生效版本',
    kpiSubjectTotal: '主体总量',
    kpiEnterpriseRatio: '企业主体占比',
    kpiCoverage: '映射覆盖率',
    listTitle: '该年度的口径版本线',
    detailTitle: '选中版本的快照说明',
    noVersion: '当前年度暂无版本记录。',
    statusDraft: '草稿',
    statusPublished: '已发布',
    statusArchived: '已归档',
    currentActiveLabel: '当前生效',
    tabDefinition: '口径定义',
    tabImpact: '影响分析',
    tabDiff: '差异对比',
    tabLog: '变更日志',
    ruleVersionLabel: '规则版本',
    batchRangeLabel: '批次范围',
    externalImportLabel: '包含外部导入',
    externalBatchCountLabel: '外部导入批次数',
    changeNoteLabel: '变更说明',
    yes: '是',
    no: '否',
    impactHint: '切换「当前生效」版本后，以下页面在未单独指定版本时，默认按新版本重新汇总（原型阶段为说明文案）：',
    impactItemEnterprise: '主体库：主体总量与来源分布',
    impactItemTicket: '发票报送覆盖分析：报送覆盖与集团成员口径',
    impactItemTree: '被审企业组织：关系树节点统计口径',
    diffColMetric: '指标项',
    diffColPrev: '上一发布版本',
    diffColCurr: '当前版本',
    diffColDelta: '变化值',
    diffMetricTotal: '主体总量',
    diffMetricEnterpriseRatio: '企业主体占比',
    diffMetricCoverage: '映射覆盖率',
    diffMetricUnmatched: '未匹配数',
    noDiff: '缺少可对比的上一发布版本。',
    updatedAtLabel: '更新时间',
    updatedByLabel: '更新人',
    publishedAtLabel: '发布时间',
    publishedByLabel: '发布人',
    saveDraftBtn: '保存草稿',
    publishBtn: '发布版本',
    rollbackBtn: '回滚上一发布版本',
    archiveBtn: '归档版本',
    exportBtn: '导出版本报告',
    bannerSaved: '草稿已保存。',
    bannerExported: '版本报告导出已开始（原型）。',
    bannerDraftCreated: '已创建草稿版本 {version}。',
    bannerPublished: '版本 {version} 已发布并设为生效口径。',
    bannerRollback: '已回滚并切换至版本 {version}。',
    bannerArchived: '版本 {version} 已归档。',
    nowMock: '2026-04-26 13:50',
    currentUser: '数据治理管理员',
    defaultDraftNote: '基于当前生效版本复制创建草稿。',
  },

  enterpriseLibraryUi: {
    pageTitle: '主体库',
    /** 原页顶两段说明合并为一条，减少占高 */
    pageIntroMerged:
      '全量主体主数据（组织/自然人）：来源与批次血缘；发票侧「更名（发票事实）」可展开，与机构类别编码治理分开。本页为「主数据目录」不按统计年度拆行，购销角色与年度在专题/事实层。更名须先「重建更名信号」；「主体信息需复核」来自主体分类推断规则，与更名无关。',
    moreTipsToggle: '查看更多操作提示',
    lessTipsToggle: '收起操作提示',
    prototypeNote:
      '本库为统一主体库：包含组织机构主体（依据 GB 32100-2015）与自然人主体（含临时纳税人），按不同规则分域管理并集中检索分析。',
    importExternalBtn: '导入外部主体数据',
    goToDwdToDimBuildBtn: 'DWD→DIM · 归集主体',
    goToDwdToDimBuildHint: '在加工中心 DWD→DIM 从发票头归集主体主数据',
    goToDwdToDimRecomputeBtn: 'DWD→DIM · 重算分类',
    goToDwdToDimRecomputeHint: '在加工中心 DWD→DIM 重算机构类别与主体关联',
    importModalTitle: '导入外部主体数据',
    modalClose: '关闭',
    modalCancel: '取消',
    importPickFile: '选择本地文件',
    importDropTitle: '拖拽或点击选择导入文件（.csv / .xls / .xlsx）',
    importDropHint:
      '支持 .csv / .xlsx：需含「主体名称」列；可选「纳税人识别号/统一社会信用代码」「主体类型」「主体类别编码」。数据写入本地 DuckDB 的 dim_subject_master。',
    importModalTip:
      '导入策略：按识别号（若有）与规范化名称生成稳定 subject_id 去重；同主体再次导入时更新最近批次与名称。若主体已由发票 DWD 归集，则保留其首次来源为「平台计算」并仅更新最近导入信息。',
    importConfirmBtn: '开始导入',
    importNeedFile: '请先选择导入文件。',
    importSuccessHint: '导入完成，已归并写入 {count} 个主体（按识别号+名称稳定去重）。',
    importFailed: '外部主体导入失败',
    importPartialRejectHint: '另有 {n} 行被拒收',
    importConfirmBusy: '导入中…',
    kpiTotal: '主体总数',
    kpiEnterprise: '组织机构主体',
    kpiPerson: '自然人主体',
    kpiCategoryNeedsReview: '主体信息需复核',
    /** 悬停/读屏：点击 KPI 卡片应用列表筛选 */
    kpiTotalClickHint: '点击查看全部 {count} 条主体明细',
    kpiTotalClickHintActive: '再次点击取消「主体类型」筛选（当前：全部主体）',
    kpiEnterpriseClickHint: '点击查看 {count} 条组织机构主体明细',
    kpiEnterpriseClickHintActive: '再次点击取消「组织机构主体」筛选',
    kpiPersonClickHint: '点击查看 {count} 条自然人主体明细',
    kpiPersonClickHintActive: '再次点击取消「自然人主体」筛选',
    kpiCategoryNeedsReviewClickHint: '点击查看 {count} 条主体信息需复核明细',
    kpiCategoryNeedsReviewClickHintActive: '再次点击取消「仅主体信息需复核」筛选',
    kpiRenameSignalSubjects: '有更名边的主体（发票）',
    kpiRenameSignalClickHint: '点击查看 {count} 条有更名边的主体明细',
    kpiRenameSignalClickHintActive: '再次点击取消「有更名边」筛选',
    /** 说明 KPI 与下方「主体类型」筛选不同步，避免误解 */
    kpiScopeHint:
      '说明：上方统计为当前「数据来源」与「主体检索」关键词下的全库主体分域（不受下方「主体类型」筛选影响）；点击卡片可快速套用对应筛选；表格与「筛选共 N 条」仍随筛选变化。',
    filterTitle: '筛选条件',
    filterReset: '重置筛选',
    renameSignalLabel: '更名信号',
    renameSignalAll: '全部',
    renameSignalYes: '有更名边',
    renameSignalNo: '无更名边',
    categoryReviewLabel: '主体信息复核',
    categoryReviewAll: '全部',
    categoryReviewYes: '仅主体信息需复核',
    categoryReviewNo: '排除需复核',
    rebuildRenameBtn: '重建更名信号',
    rebuildRenameBusy: '重建中…',
    showTechFieldsLabel: '在表格中显示技术字段（快照 ID、构建 run、规则版本、类别治理备注、质量）',
    keywordLabel: '主体检索',
    keywordPlaceholder: '主体名称 / 规范化名称 / 识别号 / subject_id（子串模糊）',
    subjectTypeLabel: '主体类型',
    subjectTypeAll: '全部主体',
    subjectTypeEnterprise: '组织机构主体',
    subjectTypePerson: '自然人主体',
    sourceTypeLabel: '数据来源',
    sourceTypeAll: '全部来源',
    sourceTypePlatform: '平台计算',
    sourceTypeExternal: '外部导入',
    subjectCategoryLabel: '主体类别',
    subjectCategoryAll: '全部类别',
    /** 筛选项来自 /api/subject-library/org-category-options（与 YAML 同步） */
    subjectCategoryOptionsLoadError: '类别选项加载失败（请检查 subject_category*.yaml 或重启本地 API）',
    ingestFromDwdBtn: '从 DWD 归集主体',
    ingestFromDwdBusy: '归集中…',
    batchLabel: '批次检索',
    batchPlaceholder: '输入最近批次号',
    tableTitle: '主体清单',
    /** 表格下方汇总：{count} 为当前筛选条件下库内总行数（非仅本页） */
    filterTotalHint: '筛选共 {count} 条',
    tablePageSizeLabel: '每页',
    tablePagePrev: '上一页',
    tablePageNext: '下一页',
    tablePageOf: '第 {page} / {pages} 页',
    colSubjectName: '主体名称',
    colSubjectNo: '主体识别号',
    colSourceType: '数据来源',
    colSubjectType: '主体类型',
    colSubjectCategory: '主体类别编码',
    colSubjectCategoryName: '类别名称',
    /** 表头跨「摘要 + 展开」两列，感知上合一 */
    colRenameSection: '更名（发票事实）',
    renameActionExpand: '查看',
    renameActionCollapse: '收起',
    renameTimelineTitle: '明细（全历史 · 发票事实）',
    colTechSnapshot: '快照 ID',
    colTechBuildRun: '构建 run',
    colTechRuleVer: '规则版本',
    colTechCategoryNote: '类别治理备注',
    colTechQuality: '质量',
    colLastBatch: '最近批次',
    /** 打开弹窗查看 dwd_inv_header 全历史匹配票 */
    colInvoiceEvidence: '关联发票',
    invoiceEvidenceOpen: '查看',
    invoiceModalTitle: '关联发票（全历史）',
    invoiceModalScopeHint:
      '按主体识别号与发票头销方/购方税号（同一套归一化）匹配；默认按票面日期降序分页加载。',
    invoiceModalLoadError: '加载失败',
    invoiceModalEmpty: '暂无匹配的发票头记录。',
    invoiceModalPagePrev: '上一页',
    invoiceModalPageNext: '下一页',
    invoiceModalPageOf: '第 {page} / {pages} 页，共 {total} 条',
    invoiceColFpdm: '发票代码',
    invoiceColFphm: '发票号码',
    invoiceColSdfphm: '数电号码',
    invoiceColXfmc: '销方名称',
    invoiceColGfmc: '购方名称',
    invoiceColKprq: '开票日期',
    invoiceColStatYear: '年度',
    invoiceColJshj: '价税合计',
    colRepairAction: '数据修正',
    repairModalTitle: '人工数据修正',
    repairNoUndoNote:
      '保存后立即生效，不可撤销；若误操作可再次打开本窗口修改。操作会写入审计表，便于追溯。',
    repairSubjectTypeLabel: '主体类型（库内 subject_category）',
    repairOrgCategoryLabel: '主体类别编码（org_category）',
    repairOrgCategoryHint:
      '与当前行一致表示不修改；清空并保存可将编码置空。下拉选项与「主体类别」规则配置（启用项）同步，无需手写维护编码表。',
    repairOrgCategoryYamlName: 'YAML 解析名称（主表仅存编码）',
    repairOrgCategoryOptionsLoading: '正在加载可选编码…',
    repairOrgCategoryOptionClear: '（清空编码）',
    repairOrgCategoryOptionUnknownPrefix: '当前值（配置中无此项）：',
    repairOrgCategoryFallbackInputHint: '未加载到配置中的类别编码，请直接输入 org_category；修复本地 API 或 YAML 后可使用下拉选择。',
    repairReasonLabel: '说明（可选）',
    repairReasonPlaceholder: '如：与工商登记核对后更正',
    repairSubmit: '保存',
    repairCancel: '取消',
    repairBusy: '保存中…',
    repairNeedChange: '请至少修改「主体类型」或「主体类别编码」之一。',
    repairSuccess: '已保存。',
    repairFailed: '保存失败',
  },

  auditRelatedEnterpriseUi: {
    prototypeBadge: '',
    pageTitle: '发票报送覆盖分析',
    pageDesc:
      '从发票侧评估企业报送覆盖情况，识别未覆盖企业并形成补录建议。入口：「维度管理 → 企业组织维度 → 发票报送覆盖分析」。分母为当年「集团年度成员」台账（dim_group_enterprise_year）中已映射到主体库 org 的成员；「已报送」为购销双向标志均为真的成员。',
    prototypeNote: '按统计年度对比集团台账成员与发票侧购销双向标志。结果用于覆盖管理与补录优先级，不直接作为风险判定。',
    auditKpiAll: '集团台账成员（映射后）',
    auditKpiRelated: '已报送（购销双向）',
    auditKpiUnreported: '尚未提报（分母内）',
    unmappedMembersHint:
      '未映射到主体库 org 的成员行：{count}（税号与主体库 org 未对齐，不参与覆盖率分母；请先在「主体库」补录或核对税号）',
    compareTitle: '筛选条件与口径',
    compareYearLabel: '年度快照',
    compareGroupLabel: '参考企业分组',
    compareGroupPlaceholder: '输入分组名称（可选）',
    compareCoverageLabel: '提报覆盖率',
    comparePropertyLevelLabel: '产权层级',
    comparePropertyLevelAll: '全部层级',
    comparePropertyParentLabel: '上级产权单位',
    comparePropertyParentPlaceholder: '输入上级产权单位（可选）',
    compareStateInvestorLabel: '国家出资企业',
    compareStateInvestorPlaceholder: '输入国家出资企业（可选）',
    enterpriseFilterLabel: '企业',
    enterpriseFilterPlaceholder: '输入企业名称 / 税号 / enterprise_id',
    compareCaliberHint:
      '口径说明：按统计年度（{year}）下「集团台账成员 dim_group_enterprise_year」与发票侧购销双向标志（dim_enterprise_year_rel，仅覆盖台账成员）比对；分母为能映射到 org 主体的成员数。',
    coreMetricsTitle: '核心指标',
    compareTotalGroup: '集团台账成员（映射后）',
    compareReported: '已提报企业',
    compareUnreported: '尚未提报企业',
    compareAuditRelated: '最近活跃报送企业',
    listViewUnreported: '尚未提报',
    listViewReported: '已报送',
    listViewAll: '全部',
    emptyByFilter: '当前筛选条件下无企业记录。',
    emptyByData: '暂无可分析数据，请先导入发票数据。',
    emptyNoGroupYear:
      '未找到「集团年度成员」数据（dim_group_enterprise_year）。请先导入或维护集团成员台账后再分析；若仅有发票年度而无成员表，本页无法计算报送覆盖。',
    reportedTitle: '已报送企业清单',
    reportedHint: '{year} 年度快照下，当前视图命中 {count} 家企业。',
    allListTitle: '企业清单（全部）',
    allListHint: '{year} 年度快照下，当前视图命中 {count} 家企业。',
    unreportedTitle: '尚未提报企业清单',
    unreportedHint: '{year} 年度快照下，当前视图命中 {count} 家企业。',
    colEnterpriseName: '企业名称',
    colTaxpayerId: '纳税人识别号',
    unreportedColMgmtLevel: '管理层级',
    unreportedColMgmtParent: '上级管理单位',
    unreportedColPropertyLevel: '产权层级',
    unreportedColPropertyParent: '上级产权单位',
    unreportedColStateInvestor: '国家出资企业',
    unreportedColLastBatch: '最近提报批次',
  },

  level1EnterpriseYearUi: {
    pageTitle: '年度一级企业名单',
    pageDesc:
      '按统计年度维护当年度的一级企业集团清单。同一 stat_year 内，集团成员表 dim_group_enterprise_year 的下属单位通过 level1_group_id 归属到名单中的一级企业；本页汇总各一级企业下属成员单位数量，并可展开查看成员明细（管理/产权层级、国家出资企业等）。',
    filterCardTitle: '筛选',
    statYearLabel: '统计年度',
    keywordLabel: '检索',
    keywordPlaceholder: '企业名称 / 识别号',
    activeOnlyLabel: '仅显示有效',
    refreshBtn: '刷新',
    listCardTitle: '{year} 年度一级企业（共 {count} 家）',
    createBtn: '新增一级企业',
    importBtn: '批量粘贴导入',
    candidatesBtn: '从集团成员表补候选',
    candidatesBusy: '加载候选…',
    loading: '加载中…',
    emptyList: '当前年度尚无一级企业记录，请新增或从集团成员表补入。',
    colOrder: '排序',
    colName: '一级企业名称',
    colId: '识别号（税号/统一码）',
    colActive: '有效',
    colRemark: '备注',
    colMemberCount: '下属成员单位',
    colStateInvestor: '国家出资企业',
    colSoeAnchor: '出资锚点（成员表）',
    memberCountHint: '{active}/{total}',
    memberCountEmpty: '—',
    colActions: '操作',
    editBtn: '编辑',
    deleteBtn: '删除',
    yes: '是',
    no: '否',
    loadFailed: '加载失败',
    saveFailed: '保存失败',
    saveSuccess: '已保存。',
    deleteFailed: '删除失败',
    deleteSuccess: '已删除。',
    deleteConfirm: '确定删除「{name}」？',
    createModalTitle: '新增一级企业',
    editModalTitle: '编辑一级企业',
    modalHint: '统计年度：{year}；同年度同识别号保存时将更新名称与属性。',
    idPlaceholder: '91370000…',
    namePlaceholder: '一级企业集团全称',
    modalCancel: '取消',
    modalSave: '保存',
    modalSaving: '保存中…',
    importModalTitle: '批量粘贴导入',
    importHint: '每行一条：识别号 + 逗号/制表符 + 企业名称。可选首行表头（含「税号」「名称」等关键字时自动跳过）。',
    importPlaceholder: '91370000MA3XXXXXX,某某集团有限公司',
    importReplaceLabel: '导入前清空该年度已有名单（慎用）',
    importConfirm: '开始导入',
    importBusy: '导入中…',
    importEmpty: '未解析到有效行，请检查格式。',
    importFailed: '导入失败',
    importSuccess: '导入完成：新增 {inserted}、更新 {updated}、拒收 {rejected}。',
    candidatesModalTitle: '集团成员表中的一级企业候选',
    candidatesModalHint:
      '以下 level1_group 出现在 dim_group_enterprise_year 中，但尚未纳入本名单。勾选后追加写入。',
    candidatesEmpty: '无新候选（可能尚未导入集团成员表，或候选已全部在名单中）。',
    candidatesFailed: '加载候选失败',
    candidatesNonePicked: '请至少勾选一条候选。',
    candidatesAddBtn: '加入名单',
    candidatesAdded: '已加入 {n} 家一级企业。',
    copyFromPrevBtn: '从上一年度复制',
    deriveFromPrevBtn: '从上一年度推导…',
    copyModalTitle: '从上一年度复制名单',
    copyModalHint:
      '将来源年度 dim_level1_enterprise_year 中的记录复制到当前筛选年度。默认同识别号合并更新；勾选「覆盖目标年度」将先清空再写入。',
    deriveModalTitle: '从上一年度推导名单',
    deriveModalHint:
      '在复制来源年度名单的基础上，用目标年度集团成员表（dim_group_enterprise_year）刷新一级企业名称，并追加成员表中新出现的一级企业。预览可编辑后保存。',
    sourceYearLabel: '来源年度',
    prevYearDefaultHint: '默认：目标年度 − 1',
    onlyActiveSourceLabel: '仅复制来源年度中「有效」记录',
    replaceTargetLabel: '覆盖目标年度已有名单（慎用）',
    copyConfirmBtn: '确认复制',
    copyBusy: '复制中…',
    copyFailed: '复制失败',
    copySuccess: '复制完成：新增 {inserted}、更新 {updated}。',
    copySkipped: '来源年度无记录可复制。',
    derivePreviewBtn: '刷新预览',
    derivePreviewBusy: '生成预览…',
    derivePreviewFailed: '预览失败',
    derivePreviewEmpty: '来源年度无记录；若需仅从集团成员表补入，请使用「从集团成员表补候选」。',
    deriveSaveBtn: '保存推导结果',
    deriveSaveBusy: '保存中…',
    deriveSaveSuccess: '推导结果已保存：新增 {inserted}、更新 {updated}。',
    colDeriveHint: '推导说明',
    colInclude: '纳入',
    deriveRowExtra: '集团新增',
    deriveRowExists: '目标年已有',
    viewMembersBtn: '查看下属',
    membersModalTitle: '{year} · {name} 下属成员单位',
    membersModalHint: '来源 dim_group_enterprise_year，level1_group_id 与一级企业识别号同口径对齐。',
    membersLoading: '加载成员…',
    membersEmpty: '该一级企业在本年度集团成员表中无下属单位记录。',
    membersLoadFailed: '加载下属成员失败',
    membersColName: '企业名称',
    membersColId: '识别号',
    membersColActive: '有效成员',
    membersColMgmtLevel: '管理层级',
    membersColMgmtParent: '上级管理单位',
    membersColEquityLevel: '产权层级',
    membersColEquityParent: '上级产权单位',
    membersColStateInvestor: '国家出资企业',
    membersFilterPlaceholder: '检索成员名称 / 识别号',
  },

  auditedEnterpriseLedgerUi: {
    prototypeBadge: '界面原型',
    pageTitle: '管理与产权层级信息',
    pageDesc:
      '被审企业数据来源于用户手工维护或模板导入，写入本地 DuckDB（dim_audited_enterprise_registry），不依赖发票明细。用于维护企业基本信息、管理层级、产权层级及国家出资企业口径。可在「批量导入」中加载演示种子以快速体验。',
    pageNote: '支持“非国资”录入；每个企业对应单一上级产权单位（含持股比例）。同一年度同一统一社会信用代码保存时执行更新。',
    kpiTotal: '在册企业总数',
    kpiListedCompany: '上市公司',
    kpiOverseasEnterprises: '境外企业',
    kpiMgmtParentMaintained: '上级管理单位已维护',
    kpiEquityParentMaintained: '上级产权单位已维护',
    kpiMainBusinessMaintained: '主业情况已维护',
    tableTitle: '被审企业主数据清单',
    tableHint: '展示口径为 {year} 快照年度。后续接入批量导入、字段校验与版本留痕。',
    snapshotFilterLabel: '快照年度',
    stateInvestorFilterLabel: '国家出资企业',
    stateInvestorFilterPlaceholder: '输入国家出资企业名称',
    enterpriseFilterLabel: '企业',
    enterpriseFilterPlaceholder: '输入企业名称或统一社会信用代码关键字',
    tableEmpty: '当前筛选条件下无匹配企业。',
    codeInputPlaceholder: '统一社会信用代码，如 91370000…',
    nameInputPlaceholder: '输入企业名称',
    domesticOverseasInputPlaceholder: '如 境内、境外',
    currencyInputPlaceholder: '如 CNY',
    yesNoInputPlaceholder: '是 / 否',
    mgmtParentInputPlaceholder: '输入上级管理单位',
    mainBusinessInputPlaceholder: '输入主业情况',
    stateStatusStateOwned: '国资',
    stateStatusNonStateOwned: '非国资',
    stateStatusUnmaintained: '未维护',
    importBtn: '批量导入',
    createBtn: '手工新增',
    createModalTitle: '手工新增被审企业',
    importModalTitle: '批量导入被审企业',
    modalClose: '关闭',
    modalCancel: '取消',
    modalSubmit: '保存',
    createModalHint: '当前为原型交互壳：将校验“统一社会信用代码 + 快照年度”唯一性，并支持非国资与单一上级产权单位录入。',
    importDropTitle: '拖拽或点击选择导入文件（.xlsx）',
    importDropHint: '建议使用“被审企业模板”：包含基础信息、管理关系、产权关系、国家出资企业字段。',
    importPickFile: '选择本地文件',
    importModalTip:
      'Excel 全量解析导入仍在迭代。当前可将《产权登记》导出等数据经转换后写入库；亦可点击下方按钮仅加载内置演示数据（会替换此前由演示写入的行，不影响手工保存的企业）。',
    importConfirmBtn: '开始导入',
    bootstrapDemoBtn: '加载演示数据',
    loadFailed: '数据加载失败',
    saveFailed: '保存失败',
    bootstrapDemoOk: '演示数据已写入本地库',
    bootstrapDemoFail: '演示数据加载失败',
    colSnapshotYear: '快照年度',
    colCode: '统一社会信用代码',
    colName: '企业名称',
    colDomesticOverseas: '境内/境外',
    colDetailAddress: '详细地址',
    colCurrency: '币种',
    colRegisteredCapital: '注册资本',
    colRegistrationDate: '注册日期',
    colNationalEconomyIndustryMajor: '国民经济行业大类',
    colEnterpriseCategory: '企业类别',
    colSasacAuthority: '所属国资监管机构',
    colSasacRelation: '与国资监管机构的关系',
    colConsolidatedReporting: '是否并表',
    colListedCompany: '是否上市公司',
    colMainBusiness: '主业情况',
    colMgmtLevel: '管理层级',
    colMgmtParent: '上级管理单位',
    colEquityLevel: '产权层级',
    colStateInvestor: '国家出资企业',
    stateInvestorInputPlaceholder: '输入国家出资企业名称（仅“国资”状态必填）',
    colShareholders: '上级产权单位',
    equityParentNamePlaceholder: '输入上级产权单位',
    equityParentRatioPlaceholder: '持股比例（%）',
  },

  auditedEnterpriseManageTreeUi: {
    prototypeBadge: '界面原型',
    pageTitle: '管理关系树',
    pageDesc: '按“管理关系”展示被审企业层级结构，支持按年度快照查看组织路径与层级展开。',
    pageNote: '默认展示“按年度快照”版本，后续接入节点搜索、展开记忆和节点详情侧栏。',
    moreTipsToggle: '查看更多操作提示',
    lessTipsToggle: '收起操作提示',
    filterYearLabel: '年度',
    filterStateInvestorLabel: '国家出资企业',
    filterEnterpriseLabel: '企业',
    filterYearAll: '全部年度',
    filterStateInvestorAll: '全部国家出资企业',
    filterEnterprisePlaceholder: '输入企业名称关键字',
    filterReset: '重置筛选',
    filterEmpty: '当前筛选条件下无匹配节点。',
    loadFailed: '数据加载失败',
    loadEmptyHint: '暂无台账数据。请先在「管理与产权层级信息」页导入演示种子或手工新增。',
    nodeCountLabel: '节点数',
    exportCurrentNodes: '导出当前节点',
    exportFileNamePrefix: '管理关系树',
    exportSuccess: '已导出',
    exportFailed: '导出失败，请稍后重试。',
    treeCardTitle: '管理关系树视图',
    nodeDetailTitle: '节点详情',
    nodeNameLabel: '节点名称',
    nodeLevelLabel: '层级',
    nodeParentLabel: '上级节点',
    nodeSnapshotLabel: '快照年度',
    nodeNoteLabel: '说明',
    nodeDetailEmpty: '请先选择左侧节点查看详情。',
  },

  auditedEnterpriseEquityTreeUi: {
    prototypeBadge: '界面原型',
    pageTitle: '产权关系树',
    pageDesc: '按“产权关系”展示被审企业股权链路，支持一个企业挂接多个上级产权单位（多股东）。',
    pageNote: '默认展示“按年度快照”版本，后续接入持股比例、控制关系类型与穿透层级开关。',
    moreTipsToggle: '查看更多操作提示',
    lessTipsToggle: '收起操作提示',
    filterYearLabel: '年度',
    filterStateInvestorLabel: '国家出资企业',
    filterEnterpriseLabel: '企业',
    filterYearAll: '全部年度',
    filterStateInvestorAll: '全部国家出资企业',
    filterEnterprisePlaceholder: '输入企业名称关键字',
    filterReset: '重置筛选',
    filterEmpty: '当前筛选条件下无匹配节点。',
    loadFailed: '数据加载失败',
    loadEmptyHint: '暂无台账数据。请先在「管理与产权层级信息」页导入演示种子或手工新增。',
    nodeCountLabel: '节点数',
    exportCurrentNodes: '导出当前节点',
    exportFileNamePrefix: '产权关系树',
    exportSuccess: '已导出',
    exportFailed: '导出失败，请稍后重试。',
    treeCardTitle: '产权关系树视图',
    nodeDetailTitle: '节点详情',
    nodeNameLabel: '节点名称',
    nodeLevelLabel: '层级',
    nodeParentLabel: '上级节点',
    nodeSnapshotLabel: '快照年度',
    nodeNoteLabel: '说明',
    nodeDetailEmpty: '请先选择左侧节点查看详情。',
  },

  auditedEnterpriseRelationUi: {
    prototypeBadge: '界面原型',
    pageTitle: '管产关系视图',
    pageDesc: '对照展示管理路径与产权路径，用于解释组织管理与股权控制关系，不对“不一致”做异常判定。',
    pageNote: '当前页面定位为关系刻画与解释分析，后续可增加关系类型标签与路径差异明细下钻。',
    tableTitle: '管产关系对照清单',
    tableHint: '“不一致”表示关系差异/特殊情形，不等价于异常。',
    recordCountLabel: '记录数',
    exportCurrentResult: '导出当前结果',
    exportFileNamePrefix: '管产关系对照',
    exportSuccess: '已导出',
    moreTipsToggle: '查看更多操作提示',
    lessTipsToggle: '收起操作提示',
    exportFailed: '导出失败，请稍后重试。',
    filterYearLabel: '年度',
    filterStateInvestorLabel: '国家出资企业',
    filterEnterpriseLabel: '企业',
    filterYearAll: '全部年度',
    filterStateInvestorAll: '全部国家出资企业',
    filterEnterprisePlaceholder: '输入企业名称关键字',
    filterReset: '重置筛选',
    filterEmpty: '当前筛选条件下无匹配记录。',
    loadFailed: '数据加载失败',
    loadEmptyHint: '暂无台账数据。请先在「管理与产权层级信息」页导入演示种子或手工新增。',
    colName: '企业名称',
    colSnapshotYear: '快照年度',
    colMgmtPath: '管理路径',
    colEquityPath: '产权路径',
    colRelationType: '关系类型',
  },

  auditedEnterpriseContributionUi: {
    prototypeBadge: '界面原型',
    pageTitle: '国家出资企业参股情况',
    pageDesc:
      '维护被审企业体系内国家出资企业参股、认缴与持股比例等台账数据，写入本地 DuckDB。支持手工新增与演示种子导入。',
    pageNote: '数据按快照年度维护；保存时按统一社会信用代码与年度做更新。',
    loadFailed: '加载失败',
    saveFailed: '保存失败',
    bootstrapDemoFail: '演示种子导入失败',
    bootstrapDemoOk: '演示种子已导入',
    importBtn: '批量导入',
    createBtn: '手工新增',
    kpiRelationRows: '关系行数',
    kpiInvestees: '被投资企业数',
    kpiContributors: '出资方主体数',
    tableTitle: '参股情况清单',
    tableHint: '展示口径为 {year} 快照年度。',
    snapshotFilterLabel: '快照年度',
    investeeFilterLabel: '被投资企业',
    investeeFilterPlaceholder: '输入企业名称关键字',
    colSnapshotYear: '快照年度',
    colUnifiedCreditCode: '统一社会信用代码',
    colInvesteeName: '被投资企业名称',
    colStateInvestorEnterprise: '国家出资企业',
    colStateInvestorUnifiedCreditCode: '国家出资企业统一码',
    colContributorName: '出资方名称',
    colContributorOrgCode: '出资方组织代码',
    colContributorCategory: '出资方类别',
    colContributionInfo: '出资情况说明',
    colRelationToTarget: '与标的企业关系',
    colCurrency: '币种',
    colSubscribedAmount: '认缴金额（万元）',
    colShareRatio: '持股比例',
    tableEmpty: '当前条件下无记录。',
    createModalTitle: '手工新增参股记录',
    modalClose: '关闭',
    unifiedCreditCodePlaceholder: '91370000…',
    createModalHint: '请核对统一社会信用代码与金额口径后再提交。',
    modalCancel: '取消',
    modalSubmit: '保存',
    importModalTitle: '批量导入参股台账',
    importDropTitle: '选择本地文件',
    importDropHint: '支持 CSV / Excel；可先使用演示种子体验流程。',
    importPickFile: '选择文件',
    bootstrapDemoBtn: '导入演示种子',
    importModalTip: '演示数据仅用于界面联调，生产环境请替换为真实台账。',
    importConfirmBtn: '开始导入',
  },

  auditedEnterpriseInvoiceLinkUi: {
    prototypeBadge: '界面原型',
    pageTitle: '企业→票（主体映射）',
    pageDesc:
      '从企业侧核对发票命中情况，判断企业主体与发票数据是否建立稳定映射。与「维度管理 → 企业组织维度」下各台账/树视图同属组织维度能力；统一主体与类别在侧栏「主体库」维护，本页专注台账主体与发票纳税人标识的映射核对。',
    pageNote: '匹配优先级：统一社会信用代码/税号 > 企业名称兜底。未命中表示待补充映射或票据覆盖不足，不直接判定为异常。',
    kpiMatched: '代码一对一匹配',
    kpiFallback: '名称兜底匹配',
    kpiPending: '待匹配',
    kpiUnmaintained: '国家出资未维护',
    tableTitle: '主体映射结果明细',
    tableHint: '当前筛选命中 {count} 条。建议优先处理“待匹配”与“名称兜底匹配”记录，提升映射稳定性。',
    emptyByFilter: '当前筛选条件下无映射记录。',
    emptyByData: '暂无可分析数据，请先导入或完成映射配置。',
    statusFilterLabel: '匹配状态',
    stateCapitalFilterLabel: '国家出资状态',
    reasonFilterLabel: '未匹配原因',
    colName: '企业名称',
    colCode: '统一社会信用代码',
    colStateCapitalStatus: '国家出资状态',
    colMatchKey: '命中匹配键',
    colLinkedTaxpayerId: '关联税号',
    colPendingReason: '未匹配原因',
    colMatchStatus: '匹配状态',
  },

  taxCodeLibraryUi: {
    prototypeBadge: '界面原型',
    tabList: '编码表与导入',
    tabHierarchy: '税收分类层级树',
    pageTitle: '编码库管理',
    pageDesc:
      '维护 dim_tax_code 编码库：支持查看编码层级、名称与导入质量（clean_status），并可按批次/会话进行筛选。',
    resultPageTitle: '税收分类层级树',
    resultPageDesc:
      '结果查看页：聚焦税收分类树与筛选结果浏览（按货物和劳务名称/按商品和服务分类、层级展开、全屏、辅助线与血缘字段）。',
    resultPageNote: '当前页用于结果核对与分析；导入、重算风险与回执请在「编码库管理」中操作。',
    prototypeNote:
      '当前为高保真界面壳：表格字段已与 dim_tax_code 口径对齐；数据版本与导入策略会记住在本浏览器会话内；须先选择本地编码表文件再执行导入。全量重建会 DELETE 后批量写入 DuckDB（仅校验则 dry_run 不落库）。',
    kpiTotal: '编码总数（当前筛选）',
    kpiLeafOnly: '末级编码（当前筛选）',
    kpiInvalidCode: '编码有误',
    kpiDuplicateCode: '编码重复',
    qualityAlert: '当前筛选下存在异常：编码有误 {invalid} 条，编码重复 {duplicate} 条。',
    qualityAlertAction: '一键只看异常',
    importCardTitle: '导入配置（DIM 税收分类）',
    importDataVersionLabel: '数据版本',
    importStrategyLabel: '导入策略',
    importStrategyFullRebuild: '全量重建（DROP + CREATE + 全量INSERT）',
    importStrategyDryRun: '仅校验与预览（不落库）',
    importPickFile: '选择本地文件',
    importClearPickedFile: '清除已选文件',
    importSubmitting: '提交中…',
    importErrVersion: '请填写数据版本。',
    importErrFile: '请先选择要导入的本地文件（csv / xls / xlsx）。',
    importErrFileDismissHint: '提示会在焦点变化或点击「选择本地文件」后自动收起。',
    importResponseEmpty: '请求已完成，但未返回说明文案。',
    importPersistHint: '数据版本与导入策略会保存在浏览器会话（sessionStorage），刷新页面仍保留。',
    taxRowsLoading: '正在从 DuckDB 加载 dim_tax_code…',
    taxRowsEmpty: '暂无数据。请先执行「全量重建」导入，或检查本地 API / 数据库连接。',
    taxRowsLoadError: '加载 dim_tax_code 失败',
    reapplyRiskBtn: '按 YAML 重算风险标签',
    reapplyRiskBusy: '重算中…',
    reapplyRiskHint:
      '修改 config/dim_tax_code_risk_rules.yaml 并保存后，点此将库中 audit_risk_label 与当前规则对齐（无需重新导入 Excel）。',
    reapplyRiskDone: '风险标签已按当前 YAML 更新。',
    reapplyRiskFail: '重算风险标签失败',
    importAction: '执行导入',
    openResultPage: '税收分类层级树',
    openResultHint: '导入完成后建议进入「税收分类层级树」页进行树形浏览与血缘核对。',
    importReceiptTitle: '导入回执（本次）',
    importReceiptEmpty: '尚未执行导入。执行后将在此显示新增条数、批次与会话信息。',
    importReceiptAt: '导入时间',
    importReceiptBatch: '导入批次',
    importReceiptSession: '导入会话',
    importReceiptRows: '新增记录',
    importReceiptParsed: '解析编码',
    importReceiptInvalid: '编码有误',
    importReceiptDuplicate: '编码重复',
    importHistoryTitle: '导入记录（当前库）',
    importHistoryEmpty: '当前库暂无可展示的导入批次/会话记录。',
    importHistoryBatchCol: '批次',
    importHistorySessionCol: '会话',
    importHistoryRowsCol: '记录数',
    importHistoryVersionCol: '数据版本',
    importHistoryLatestCol: '最近导入时间',
    importHint: '读取规则：支持 csv/xls/xlsx，跳过前2行，从第3行开始；编码异常与重复会写入 clean_status。',
    filterTitle: '筛选条件',
    keywordLabel: '关键词检索',
    keywordPlaceholder: '编码 / 货物和劳务名称 / 分类简称 / 全路径',
    cleanStatusLabel: '清洗状态',
    cleanStatusAll: '全部状态',
    cleanStatusOk: '正常',
    cleanStatusInvalid: '分类编码有误',
    cleanStatusDuplicate: '分类编码重复',
    cleanStatusHelp:
      '用于导入质量治理与追溯：\n1) 分类编码有误：编码经清洗后非19位或含非法字符。\n2) 分类编码重复：同批导入中出现重复编码。\n建议：日常浏览默认隐藏该列，仅在导入验收或异常排查时开启。',
    riskLabel: '风险标签',
    riskAll: '全部风险',
    riskNormal: 'NORMAL',
    riskHigh: 'HIGH',
    abnormalOnlyToggle: '仅看敏感类目',
    showQualityColumnToggle: '显示质量列（clean_status）',
    tableTitle: '编码明细与导入血缘',
    tableHint: '当前筛选命中 {count} 条编码记录。',
    hierarchyCardTitle: '税收分类层级树',
    hierarchyHint:
      '与列表使用同一套筛选结果：按 parent_code 组装为可折叠树。按货物和劳务名称模式下节点标题取「货物和劳务名称」（goods_name）；按商品和服务分类模式下同一拓扑节点标题取「商品和服务分类简称」（goods_short_name，空则回退名称）。父级不在当前结果集中的节点显示为根并带「孤立」标记。',
    hierarchyToolbarExpandAll: '展开全部',
    hierarchyToolbarCollapseAll: '收起全部',
    hierarchyTreeModeCode: '按货物和劳务名称',
    hierarchyNodeColTitle: '树节点',
    hierarchyTaxCategoryColTitle: '商品和服务税收分类',
    hierarchyTreeModeCategory: '按商品和服务分类',
    hierarchyToolbarExpandToLevel: '展开到层级',
    hierarchyToolbarLevelLabel: '层级',
    hierarchyToolbarQuickLevelPrefix: '快捷',
    hierarchyToolbarFullscreen: '全屏',
    hierarchyToolbarExitFullscreen: '退出全屏',
    hierarchyLegendTitle: '图例',
    hierarchyLegendOk: '正常',
    hierarchyLegendInvalid: '编码有误',
    hierarchyLegendDuplicate: '编码重复',
    hierarchyLegendHigh: '敏感类目（HIGH）',
    hierarchyLegendOrphan: '孤立（父级未在结果集）',
    hierarchyGoodsNameUniqueCount: '不重复货物和劳务名称：{n}个',
    hierarchyCategoryUniqueCount: '不重复商品和服务分类：{n}个',
    hierarchyRowLevelPrefix: '层级',
    hierarchyColCode: '合并编码',
    hierarchyColName: '货物和劳务名称',
    hierarchyColDepth: '层级深度',
    hierarchyColLeaf: '末级',
    hierarchyOrphanBadge: '孤立',
    colTaxCode: '税收分类编码',
    colGoodsName: '货物和劳务名称',
    colGoodsCategory: '商品和服务分类',
    colDepth: '层级深度',
    colLeaf: '叶子节点',
    colParentCode: '父级编码',
    colPath: '全路径',
    colCleanStatus: '清洗状态',
    colRisk: '风险标签',
    colBatch: '导入批次',
    colSession: '导入会话',
    colRemark: '说明',
    filterImportBatchLabel: '导入批次（import_batch_id）',
    filterImportBatchPlaceholder: '请选择 import_batch_id',
    filterImportSessionLabel: '会话ID（import_session_id）',
    filterImportSessionPlaceholder: '请选择 import_session_id',
    leafYes: '是',
    leafNo: '否',
  },

  /** 税收分类编码 · 关联质量（治理视角） */
  taxCodeAnalysisUi: {
    prototypeBadge: '界面原型',
    pageTitle: '税收分类编码 · 关联质量',
    pageDesc:
      '面向数据治理：在 DWD 明细侧对照 dim_tax_code，监控税收分类编码（ssflbm）命中率、未匹配编码与疑似脏值规模。本页用于保障“编码可用性”，不直接输出企业风险结论。',
    prototypeNote:
      '当前为高保真原型：KPI 与示例表为演示数据；后续按 import_batch_id / stat_year 与 dwd_inv_detail 对接。',
    kpiMatchRate: '明细编码命中率（演示）',
    kpiUnmatchedLines: '未匹配明细行数（演示）',
    kpiHighRiskAmountShare: '空值或脏码占比（演示）',
    kpiTopCategoryShare: 'Top1 未匹配编码占比（演示）',
    scopeCardTitle: '分析范围',
    statYearLabel: '统计年度',
    batchKeywordLabel: '编码关键词（占位）',
    batchKeywordPlaceholder: '筛选未匹配表示例…',
    scopeHint: '正式接入后：与「ODS→DWD」批次和统计年度联动，可下钻到 DWD 明细定位问题来源。',
    unmatchedTableTitle: '未匹配或疑似异常编码（演示）',
    unmatchedTableHint: '发票明细 ssflbm 在维表中不存在、为空或格式异常，便于补维表或修正清洗规则。',
    colSsflbm: '票面税收分类编码',
    colLineCount: '涉及明细行数',
    colAmountSum: '价税合计（演示）',
    colSampleInvoices: '涉及发票数（演示）',
    nextCardTitle: '后续可接入能力',
    nextBullets: [
      '提供「未匹配编码修复」闭环：补维表、改清洗规则、重跑批次',
      '支持按来源批次 / 会话定位问题输入文件与责任人',
      '从本页跳转到「DWD数据查看」并自动带上 ssflbm 筛选条件',
    ],
  },

  /** 税收分类编码 · 企业分析（DM 视角） */
  taxCodeEnterpriseUi: {
    prototypeBadge: '界面原型',
    pageTitle: '税收分类编码 · 企业分析',
    pageDesc:
      '面向企业审计：基于 DM 企业专题数据观察税收分类结构、敏感类目暴露与月度波动，输出“具体公司”的排查优先级与可追溯样本。',
    prototypeNote:
      '当前为高保真原型：企业画像与指标为演示数据；后续将对接 dm_enterprise_taxcode_profile 等企业主题模型。',
    kpiEnterpriseCoverage: '企业覆盖率（演示）',
    kpiHighRiskEnterpriseCount: '高风险企业数（演示）',
    kpiTopCategoryConcentration: 'Top1（二级类目）集中度（演示）',
    kpiMonthlyMutationRate: '月度结构突变率（演示）',
    scopeCardTitle: '分析范围',
    statYearLabel: '统计年度',
    enterpriseKeywordLabel: '企业关键词',
    enterpriseKeywordPlaceholder: '企业名称 / 纳税人识别号 / 税收分类类目',
    industryLabel: '行业或主类目',
    industryAll: '全部行业',
    scopeHint: '正式接入后：支持按企业组、行业、地区与审计任务过滤，并回链 DWD 明细样本。',
    enterpriseTableTitle: '企业税收分类画像（演示）',
    enterpriseTableHint: '当前筛选命中 {count} 家企业。',
    topCategoryRuleHint: '口径说明：Top 类目取自「商品和服务分类」第 2 层，以企业在统计窗口内该二级类目的金额占比排序，取占比最高者。',
    colEnterpriseName: '企业名称',
    colTaxpayerId: '纳税人识别号',
    colTopCategory: 'Top 类目（二级）',
    colTopCategoryRatio: 'Top 类目（二级）占比',
    colHighRiskRatio: 'HIGH 类目占比',
    colFluctuationIndex: '波动指数',
    mockScenarioLabel: '演示场景',
    mockScenarioManufacturing: '制造业',
    mockScenarioTrade: '贸易业',
    mockScenarioService: '服务业',
    mockScenarioHint:
      '切换场景仅更换 KPI 与表格中的演示数据，便于评审不同业态下的指标解释；与真实 DuckDB / DM 表无联动。',
    scenarioFocusTitle: '场景审计关注点（演示）',
    scenarioFocusManufacturing: '制造业：重点关注同一企业在“设备类目”占比持续上行且 HIGH 类目同步抬升的组合信号。',
    scenarioFocusTrade: '贸易业：重点关注“贸易经纪与代理”占比异常提升，以及跨月波动偏离行业中位数的企业。',
    scenarioFocusService: '服务业：重点关注“现代服务/咨询”集中度过高且月度突变频繁的企业，优先下钻票面样本。',
  },

  taxCodeRiskDefineUi: {
    pageTitle: '敏感类目定义',
    pageDesc:
      '通过界面直接维护 `config/dim_tax_code_risk_rules.yaml`，用于定义 dim_tax_code 的敏感类目规则（NORMAL/HIGH）。保存后可一键重算风险标签并在层级树中即时查看效果。',
    configCardTitle: '规则配置（YAML）',
    loadBtn: '重新加载',
    saveBtn: '保存规则',
    saving: '保存中…',
    loadFailed: '加载规则失败',
    saveFailed: '保存规则失败',
    saveDone: '规则已保存。',
    sourcePathPrefix: '配置路径：',
    reapplyTitle: '应用到编码库',
    reapplyHint: '保存规则后，执行一次“重算风险标签”，将 dim_tax_code.audit_risk_label 与当前规则对齐。',
    reapplyBtn: '保存后重算风险标签',
    reapplyBusy: '重算中…',
    reapplyDone: '重算完成',
    reapplyFailed: '重算失败',
    helpTitle: '规则示例与说明',
    helpBullets: [
      '按 rules 顺序匹配，命中首条即停止；全部未命中回退 default_label。',
      '支持 field_contains（字段含关键词）与 tax_code_prefix（编码前缀）两类条件。',
      '建议先小范围改词，再在“税收分类层级树”勾选“仅看敏感类目”验证效果。',
    ],
  },

  uploadZone: {
    primaryLine: '拖放 Excel 文件或文件夹到此处',
    actionHint: '或点击：',
    /** 虚线区默认行为为打开文件夹选择；内联「选择文件」仍可单选/多选文件 */
    ariaMainAction: '选择文件夹（拖拽或点此区域）；内文链接可改为选择文件',
    pickFiles: '选择文件',
    pickFolder: '选择文件夹',
    helperDefault:
      '建议 Excel 命名：{公司简称}_{进项/销项}_年度（或X月至Y月）.xlsx。选文件夹时会自动忽略打开表格产生的 ~$ 锁文件（非真实工作簿）。',
  },
} as const

export type ZhCN = typeof zhCN
